### ISSUE TITLE
Bug: The links in the header section of website are too close

### ISSUE THREAD

**Issue by utkarsh1311** [moja-global/community-website#100]
### Describe the bug.

The links mentioned in the ```hero``` div of header section of the home page look too close due to improper margin.

![Screenshot from 2021-10-05 19-27-55](https://user-images.githubusercontent.com/70108561/136037937-86afea28-19ee-41da-825c-053205d5cf6c.png)

### Describe the steps to reproduce the behavior.

Modify the margin of the links in ```hero``` div of header section so that they have proper spacing between them.

### Expected behavior.

After modifying the links will look like this

![Screenshot from 2021-10-05 19-28-42](https://user-images.githubusercontent.com/70108561/136038407-ec05af13-73df-4cca-9e58-c04ef6d7d3ff.png)

### Operating Environment

Ubuntu 20.04

### Additional Information

Please assign this issue to me.

**Comment by HarshCasper** [comment]
Thanks for taking it up @utkarsh1311 :pray: 

We are also looking for some help with re-implementations of our UI components. Please let us know if you would like to help us with the same.

**Comment by utkarsh1311** [comment]
Sure I would love to. 😊

**Comment by Eddievin** [comment]
> Thanks for taking it up @utkarsh1311 🙏
> 
> We are also looking for some help with re-implementations of our UI components. Please let us know if you would like to help us with the same.

Hey, I would like to help with this too. Which one can I start with?

**Comment by HarshCasper** [comment]
Hi @Eddievin @utkarsh1311 

I will create the issues in a few hours. You can track all of the issues being created here:

![image](https://user-images.githubusercontent.com/47351025/136048504-446d75c3-236f-4bd4-983c-3fd04bbffb9d.png)

You can join our Slack as well and drop a message on the #community-website channel.

**Comment by 17bcs1837** [comment]
> Thanks for taking it up @utkarsh1311 pray
> 
> We are also looking for some help with re-implementations of our UI components. Please let us know if you would like to help us with the same.

Hi @HarshCasper,
I would like to work on this issue as well. Waiting for the issues to be created!
