### ISSUE TITLE
Bug: Timeline not visible in Dark mode in Roadmap section

### ISSUE THREAD

**Issue by Harsh19189** [moja-global/community-website#102]
### Describe the bug.

When we switch to dark mode in the View Timeline of Projects in Roadmap Section the texts remains invisible unless we switch to light mode.

### Describe the steps to reproduce the behavior.

We can switch to any dark colour (e.g black, dark green etc.).

### Expected behavior.

The texts in Timeline should be visible in both Dark and Light mode.

### Screenshots.

![View Tmeline](https://user-images.githubusercontent.com/86603492/136055126-59aa2212-3648-4622-ac09-ff371135475d.png)

### Operating Environment

Linux mint (chrome)

**Comment by 17bcs1837** [comment]
Hi,
I would like to work on this issue. Please assign me this issue.

**Comment by Harsh19189** [comment]
I would also like to work on this issue, Please do assign this issue to me also.
