### ISSUE TITLE
Bug:  footer is not responsive for 999px and below.

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/community-website#103]
### Describe the bug.

The footer breaks for max-width 999px, the footer items should align next to each other in columns rather than in a single row.

### Describe the steps to reproduce the behavior.

-scroll down to the footer
- open chrome devTool on the landing page
- adjust the screen to 999px or lower

### Expected behavior.

Stack the footer items next to each other in columns and rows rather than having them in a single row.

### Screenshots.

![Screenshot (449)](https://user-images.githubusercontent.com/75530516/136070223-d88be1ad-02cb-4c1e-9e8e-e37e6a5ca326.png)

### Operating Environment

windows 10

**Comment by mstofirova** [comment]
Hello, Can I work on this issue please?

**Comment by HarshCasper** [comment]
> Hello, Can I work on this issue please?

I will be creating new issues soon. Please feel free to take them up :smile:
