### ISSUE TITLE
Feature Request: Create a Community Contributors Section

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#125]
### Is your feature request related to a problem? Please describe.

As of now, we only feature the Community Website contributors on the community website. We would like to ideally feature a "community-wide" contributor section where all the contributors from all moja global projects can be featured. We would ideally like to have the following:

- Name
- Profile Picture
- GitHub URL
- Projects contributed to

Some inspirations:

- https://webdriver.io/community/team
- https://verdaccio.org/contributors

### Describe the solution you'd like.

- Write a Node script that can pull all the public projects and their contributors for moja global using the GitHub API
- Define a React component that takes the JSON data and renders the contributors list on the MDX 
- Make a new page in the `community` section and add the React component there

### Describe alternatives you've considered

Alternatively, the minimal feature I would be looking for would be to have a simple JSON DB where the data can be pulled from and rendered on the React component. If the org-wide contributor list isn't doable, we can consider this approach as well and manually maintain the contributors list.

**Comment by sandeep-v1404** [comment]
Can you assign me this issue ? @HarshCasper

**Comment by HarshCasper** [comment]
> Can you assign me this issue ? @HarshCasper

Please work on the issue already assigned to you.

**Comment by HarshCasper** [comment]
> Can you please tell where the page redirect in the community section if i create a page in that section. because I'm unable to understand the routes of the community section.

Docusaurus does that automatically for us. You can either create a Markdown Page or a React page to complete that.

https://github.com/moja-global/community-website/tree/main/website/src/pages

**Comment by padmajabhol** [comment]
Can I work on this if this is still open?

**Comment by asmijafar20** [comment]
> Can I work on this if this is still open?

Working on it! If you can write the scripts using GitHub API for fetching org-wide contributors that would be great. Because I have created the manually maintained JSON file. we need to write node script if you can take this part of the issue. Because I have already written the code, I just have to rewrite some files. you can check [here](https://github.com/moja-global/community-website/pull/177) for details. @HarshCasper want your inputs for this?

**Comment by tanay123456789** [comment]
Working on it
