### ISSUE TITLE
Documentation: Migrate moja global strategic plans to community website

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#127]
### What is the current documentation state?

Currently, the strategic plans are hosted here: https://github.com/moja-global/About_moja_global/blob/master/Governance/STRATEGIC-PLANS.md

### Where is this stated?

https://github.com/moja-global/About_moja_global

### Why do you want to improve the statement?

We are migrating moja global specific docs and content over the community website. We have migrated the majority of the content over the community website and we would like to have the strategic plans as well.

### Proposed Statement

- Create a new page under the `Community` section, to add a strategic plan change.
- Upload all the PDFs under the `static/` directory.
- Reference the PDF files on the Strategic Plans page.

**Comment by AnirudhPanda** [comment]
I can take this?
