### ISSUE TITLE
CHORE: Remove duplicated `.gitignore` from the repository

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#132]
### Describe what you are trying to do and why it is not optimal.

We have two `.gitignore` on the same repository. One is present on the root ([here](https://github.com/moja-global/community-website/blob/main/.gitignore)) while the other is present on the `website` directory ([here](https://github.com/moja-global/community-website/blob/main/website/.gitignore)).

### Describe the solution you'd like.

We would ideally like to have only one `.gitignore` for the entire project. Refactor all the significant details to the root-level `.gitignore` and it would be fine.

### Additional context.

This issue is marked as `beginners-only`. People who have never contributed to the community website in general and moja global in particular are allowed to contribute. Special preference is given to the Outreachy candidates to help them get started with their first good contributions.

**Comment by HarshCasper** [comment]
> Hello @HarshCasper , if I get what you want done here, it's to copy the ".gitignore" file the website directory to the root, and delete the website directory ".gitignore" ??

Exactly.

**Comment by Amishakumari544** [comment]
Is it open to work? Can I take this?

**Comment by King-kay** [comment]
Oh!!🤦🏽..too slow

**Comment by King-kay** [comment]
I already did it ws waiting for the reply to drop pr🙃🙃..too bad
