### ISSUE TITLE
Documentation: Add hyperlinks on the `Mentorship` page

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#134]
### What is the current documentation state?

Currently, we list the mentorship and internship opportunities offered by moja global on the Mentorship page. However, we lack hyperlinks and references to the actual programs and would ideally like to fix the same.

### Where is this stated?

https://community.moja.global/community/mentorship

### Why do you want to improve the statement?

Adding more hyperlinks and references would be beneficial from an SEO perspective and will allow the potential mentees/interns to have a look at the actual programs.

### Additional context.

This issue is marked as `beginners-only`. People who have never contributed to the community website in general and moja global in particular are allowed to contribute. Special preference is given to the Outreachy candidates to help them get started with their first good contributions.

**Comment by HarshCasper** [comment]
> @HarshCasper I would like to contribute on this issue! This will be my first time contributing to documentation related issue! :)

Welcome to the community and thanks for taking it up!

**Comment by Yash-271120** [comment]
@HarshCasper I have made a pull request. Please check it! Thanx :)
