### ISSUE TITLE
CHORE: Add links on the `Get involved` section of the `Initiatives` page

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#135]
### Describe what you are trying to do and why it is not optimal.

As of now, the `Learn more` buttons for the `Get involved` section, does not direct to anywhere.

Find the initiatives page here: 

- https://community.moja.global/initiatives
- https://github.com/moja-global/community-website/blob/main/website/src/pages/initiatives.js

### Describe the solution you'd like.

 We would like to add the links so that folks can join our Slack community and have a look at our GitHub organization.

### Additional context.

This issue is marked as `beginners-only`. People who have never contributed to the community website in general and moja global in particular are allowed to contribute. Special preference is given to the Outreachy candidates to help them get started with their first good contributions.

**Comment by toth2000** [comment]
Looking into this.

**Comment by caseynv** [comment]
Hi, I am an outreachy applicant. I'd like to work on this.

**Comment by caseynv** [comment]
HI. which link do you want exactly for the Learn more? The moja community on slack or GitHub?
