### ISSUE TITLE
Create GitHub Action to test build

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#14]
## Description

Add a GitHub Action to test the application build.

**Comment by soham283** [comment]
i would like to contribute, can you please assign me this issue @HarshCasper

**Comment by aornugent** [comment]
@soham283 - how are you going with this? @sarthakkundra, can you please provide a pointer on how to run automated tests?

**Comment by Ayush7614** [comment]
@aornugent @HarshCasper i would like to work on the issue please assign me

**Comment by HarshCasper** [comment]
Hi @Ayush7614 

Thanks for taking up the issue and submitting a Pull Request for the same. Unfortunately, this Issue was on the priority list for us and we cannot further delay having the requested changes wait.

I am taking the issue myself to integrate CI pipelines for the project. Please feel free to take up any other open issue at moja global. Thanks for your contributions.
