### ISSUE TITLE
Performance: Defer Off-Screen Images (on `/` Route) 

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/community-website#144]
### Describe the bug.

The Off-Screen Images (eg. Contributors images) on the Home Page contributes to the major drawbacks of App Performance. The Proposed Solution is to `Lazy-Load` these images and render when they are visible on the screen.

### Describe the steps to reproduce the behavior.

This is observed by Lighthouse test. 
Observed in the Performance section.

### Expected behavior.

The FCP and performance can be improved if images can be loaded lazily. 
Read more [here](https://web.dev/offscreen-images/?utm_source=lighthouse&utm_medium=devtools)

### Operating Environment

Windows

### Additional Information

Can refer resources such as: https://cnpmjs.org/package/@docusaurus/plugin-ideal-image/v/2.0.0-alpha.6afa83c41

Would like to work on this issue. Please assign me.

**Comment by rehanmohiuddin** [comment]
@sohamsshah @HarshCasper pls assign it to
Me will work on this
