### ISSUE TITLE
Building a Contributors Website for Moja Global outreach

### ISSUE THREAD

**Issue by shubhamkarande13** [moja-global/community-website#15]
**Summary :** Establish a contributors website for moja global projects to welcome new and old contributors.

**Background :** A contributors website makes contributors feel at ease and guides them on how to get started and what to do in case they get stuck. GitHub repositories can sometimes be scary and hence a contributors website would be a great addition for communication. It will help to start with the onboarding process for new contributors who want to get more info about operations or strategy or want to participate in defining the strategic direction of moja global or in resolving technical or scientific discussions. 

**Details :** The website should be informal, very user-friendly (with pleasant design and UX to create a friendly atmosphere and good use of icons) and action-oriented. This website is made for contributors and should make them feel a sense of belonging in the community of moja global.

**Platform :** Not finalised yet. Need your inputs on this. Feel free to propose more options for hosting the website.
One option is Jenkins, maybe?? Need help on this. @Tlazypanda @Patamap @gmajan 

**Features :** 

- Operational procedures
- Coding styles, CI info, performance, etc.
- Outstanding issues for newcomers (good-first-issue)
- Features to be developed
- Modules to be developed
- Policy needs from users
- Longer-term strategy
- Board agendas and minutes
- TSC agendas and minutes
- Integrating with Twitter at https://twitter.com/yourfirstpr and CodeTriage www.codetriage.com to attract new contributors by highlighting first-timer issues

**Expected Outcome :** To welcome more long term contributors across all fields and helping the community grow with a healthy open-source culture.

Reference of what a Contributors Website should look like, suggested by Sneha @Tlazypanda : [PublicLab Coding Community page](https://code.publiclab.org/)

**Actions :**

- Finding the right platform for hosting the website
- @shubhamkarande13 will be taking a lead on the website
- @saloni-garg will help as an advisor and find a good designer for UI/UX
- @shubhamkarande13 will write all features user flow, Database diagram, UX/UI, infrastructure under the advice from @Tlazypanda 
- @saloni-garg will be leading an open-source mentorship program which we will test with 4 students/mentees who get a chance to show their talents or publish research papers etc.
- We are welcoming existing and new contributors to this project for suggestions or any help
- We would like senior maintainers and the board to give their suggestions about this project 

for more info: https://docs.google.com/document/d/1gsWZPvh76vLTh3cNq3eH6fhaYplAiHIioI2_OSzmsUE/edit

**Things to do :**

- Decide the hosting platform
- Make a plan of user flow of the website
- Decide the tech stack of the website
- Decide on the hero image on the landing page

more points will be added as the development continues

edit: added things to do

@Tlazypanda @Patamap @gmajan @saloni-garg

**Comment by HarshCasper** [comment]
> @aornugent That seems like a perfect solution.
> 
> @sarthakkundra Could you move this issue to the GSoD repo?

Transferred it here.

**Comment by gmajan** [comment]
Just a quick response to the hosting options: We have free hosting on the
servers of Climate Advisers where we also host our regular website. You can
choose the platform and run it on their servers.
Looks great!

**Comment by sarthakkundra** [comment]
@gmajan Sounds great!

**Comment by aornugent** [comment]
Hey @sarthakkundra - can you please provide an update in this? Let us know how we can help!

**Comment by sarthakkundra** [comment]
Hey @aornugent. I thought we finalised this on our call that we'll apply for Vercel's grant for our front-end platform  and since it's a static site, we don't need any servers. Once the site is hosted on Vercel. We can use the subdomain `community.moja.global` to put it live. Let me know if I'm missing anything.

**Comment by aornugent** [comment]
Thanks! I'm asking to continue the discussion in a public forum.

Can you please send me a draft of the application, when you're ready? We should definitely qualify.

**Comment by sarthakkundra** [comment]
I'll get on it by around 25-26 June. Once the website is near ready. I'll open an issue for the application and link it here so that everyone can pitch in.
