### ISSUE TITLE
Documentation: moja-global charter link is not working

### ISSUE THREAD

**Issue by Ruchip16** [moja-global/community-website#150]
### What is the current documentation state?

In the website, when I navigated to docs/about-moja-global, I observed that read the moja-global charter link when clicked is not working and gives a page not found an error 

![image](https://user-images.githubusercontent.com/72685035/137089068-01e66010-1a4c-4d89-9585-337cbf0927a6.png)

### Where is this stated?

![image](https://user-images.githubusercontent.com/72685035/137089126-87f8dd29-cd4f-4a59-b5ce-ed1391b2b966.png)

### Additional context.

CC @HarshCasper which link should be navigated to this one?

**Comment by HarshCasper** [comment]
Hi @Ruchip16 

Here is the moja global charter: https://github.com/moja-global/community-website/blob/main/website/static/moja-global-charter.pdf

You can reference it by the relative path and this would work!

**Comment by Ruchip16** [comment]
@HarshCasper the issue has been resolved as I viewed now other contributor added the pdf there itself in the development folders, hence closing this issue now
