### ISSUE TITLE
Documentation: Incorrect links in repository README

### ISSUE THREAD

**Issue by Mukulikaa** [moja-global/community-website#157]
Currently, the first two links of [Contribution Guides](https://github.com/moja-global/community-website#contribution-guides) lead to [Contributing Guidelines](https://community.moja.global/community/contributing) instead of the intended sub-sections. I think this is because of a slight mistake in the URL.

**Comment by HarshCasper** [comment]
Hi @Mukulikaa 

Thanks for pointing out. They should follow up to these links:

- https://community.moja.global/community/community-website-contributions#writing-new-blogs
- https://community.moja.global/community/community-website-contributions#adding-new-documentation

Can you make a PR for the same? Thanks!

**Comment by Mukulikaa** [comment]
Closed #157 by #172.
