### ISSUE TITLE
Bug: `moja global` community logo not visible on the NavBar

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#160]
### Describe the bug.

The `moja global` community logo is not visible on the NavBar.

### Expected behavior.

The logo should be visible.

### Screenshots.

Before: 

![image](https://user-images.githubusercontent.com/47351025/137527882-73ac7fcc-f858-4553-b395-2829a7c81c79.png)

After:

![image](https://user-images.githubusercontent.com/47351025/137527902-6d763204-86c0-4edd-912b-aff32fed7847.png)

### Operating Environment

Chrome Version 93.0.4577.82 (Official Build) (64-bit)

### Additional Information

The bug was introduced via the https://github.com/moja-global/community-website/pull/159 PR.

**Comment by Amishakumari544** [comment]
Can I take this??
