### ISSUE TITLE
Feature Request: Add a Workshops/Talks Page for the Community Website

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#162]
### Is your feature request related to a problem? Please describe.

Moja global recently engaged in a series of workshops at the United Nations Framework Convention on Climate Change where we introduced a wide audience about Moja global, our open source community, FLINT, Reporting tools, examples, and more.

We have released all the presentations and videos from the UNFCCC workshops on our YouTube channel. You can find them here: https://www.youtube.com/playlist?list=PL_WECUlMWiUlX_BjC33_fr5oAOdf1weB0

For beginners, these videos can be the best way of getting started up. You will not only know about the various projects under the Moja global umbrella but also about our open-source model, structure, and the wider community!

### Describe the solution you'd like.

We would like to have a Talks/Workshops page where all of these can be centrally published. The data can be fed through a JSON file that stores all of our talks/workshop engagement which can be referred for future use.

**Comment by sandeep-v1404** [comment]
Can I work on this issue? @HarshCasper

**Comment by Namyalg** [comment]
I would like to work on this
