### ISSUE TITLE
Feature Request: Create a Community Calendar section

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#163]
### Is your feature request related to a problem? Please describe.

As of now, we have an initiatives page where our upcoming meetups and events are documented and organized: https://community.moja.global/initiatives

However these are hard to maintain, and are not UX-friendly. We would like to have a community calendar implementation so that it becomes easy for us to know and understand our upcoming meetups and events for a general accessibility.

### Describe the solution you'd like.

We can potentially use:

- https://dptoot.github.io/react-event-calendar/
- https://www.npmjs.com/package/react-full-event-calendar
- https://www.npmjs.com/package/react-big-calendar

### Additional context.

We would like the data to be supplied by either a JSON file which can be easily edited or a Google Sheet which can be maintained by both technical & non technical users.

**Comment by shivani6320** [comment]
Hey @HarshCasper ! I have little confusion about the final outcome of this issue. Should I use particular react based calendar as mentioned by forking it and editing later or just simply maintain a google sheet which can be easily accessed or edited by admins?  Also, where should I put it - into a specific folder or just place its link in comment while making final pull request?

**Comment by HarshCasper** [comment]
> Hey @HarshCasper ! I have little confusion about the final outcome of this issue. Should I use particular react based calendar as mentioned by forking it and editing later or just simply maintain a google sheet which can be easily accessed or edited by admins? Also, where should I put it - into a specific folder or just place its link in comment while making final pull request?

The first preference. We need to have a Calendar component that can be easily used to put forward our community calendar. You can apply your own intuition to understand what can be the best for the purpose of the community members :)

**Comment by Amishakumari544** [comment]
hey @HarshCasper  if @shivani6320  is not working may I try this?

**Comment by Palaksharma23** [comment]
i would like to take up this issue , if no one is working on it.

**Comment by sohamsshah** [comment]
Sure, go ahead!
