### ISSUE TITLE
Documentation: Add Documentation Working Group in the `Community` section

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#167]
### What is the current documentation state?

We would need to migrate the Documentation Working group description and purpose to the community website. While we can remove the `About moja global` section, rest of the sections would remain the same.

### Where is this stated?

https://github.com/moja-global/Google.Season.of.Documentation/blob/master/Documentation-Working-Group-Proposal.md

**Comment by Mukulikaa** [comment]
Oops, @HarshCasper  I mentioned the wrong issue in my PR (#172); it was supposed to be #157. I guess you'll have to reopen this issue 🙂.

**Comment by Amishakumari544** [comment]
@asmijafar20  are you working on it ??

**Comment by madhhuurrii** [comment]
Hi, @HarshCasper is this issue available? I would like to contribute!

**Comment by Palaksharma23** [comment]
and I want to clarify in which section do I need to migrate the Documentation Working group description and purpose in community website and from where do I need to remove the about moja global section.
