### ISSUE TITLE
Bug: Fix the 'Know the Community' for smaller screen.

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/community-website#171]
### Describe the bug.

The 'Know the community" section breaks for max-width 999px. 

### Describe the steps to reproduce the behavior.

Go to the particular section and inspect with max width 999px or lower.

### Expected behavior.

The children divs should align next to each other with a minimum of 2 divs.

### Screenshots.

![SScreenshot (455)](https://user-images.githubusercontent.com/75530516/137585836-90bd6540-1eac-48b1-8745-9e9daa492f9e.png)

### Operating Environment

windows 10

**Comment by helper-uttam** [comment]
Hey @padmajabhol, are you working on this? If not then can I?
