### ISSUE TITLE
Communication Suggestion: change the name "docs" on repo to "projects/docs"

### ISSUE THREAD

**Issue by katzesoundz** [moja-global/community-website#184]
### Describe how we are communicating and why it is not optimal.

I was working on the issue #166 and it took me a while until I figure out where projects section was located on the community repo. 
I couldn't find it because it was named as "docs", but all the other sections were named just like in the community web site. 

### Describe the solution you'd like.

change the name "docs" on the community repo  to "projects/docs", so it keeps in a way how it is named so far, but also adds more information so people who would like to work on this section could find it more easily.

### Describe alternatives you've considered.

or change it to "projects" or "docs/projects".

**Comment by katzesoundz** [comment]
if you consider this issue relevant, please assign it to me.

**Comment by YashKandalkar** [comment]
@HarshCasper Hello! Is this still up for taking? Having the links like "/projects/about-moja-global" etc. under the "Projects" nav item makes sense rather that the current docs/.
I managed to change the default `docs` folder of `docusaurus` to `projects` and covered all the links that referred to `docs`. 
Should I make a PR for this?
