### ISSUE TITLE
Which projects to put initially on the Community Website?

### ISSUE THREAD

**Issue by sarthakkundra** [moja-global/community-website#19]
These projects will be featured in the `Projects` section of the website where for each project the user can see an :- 

1. About
2. Setting Up
3. Usage
4. Learn More

This thread is to discuss which projects we want to add :- 
- [ ] FLINT

CC :- @aornugent @HarshCasper @Tlazypanda

**Comment by shubhamkarande13** [comment]
Some suggestions:

- FLINT Example
- FLINT JSON Interface
- FLINT Cloud
- FLINT Visualization Tool (Taswira)
- FLINT Reporting Tool 
- FLINT Agricultural Soils Module
- GCBM Environmentally Sensitive Forest Module

**Comment by aornugent** [comment]
I suggest a separate FLINT modules section, including GCBM, FLINT Example and Agricultural soil, but also the other modules described by Mohit.

Also, @waridrox published a content map for the community website a while ago - do you still have this for reference? I think an introduction to the keystone projects is a great idea but the setup and usage instructions are already covered at docs.moja.global. Maybe we can keep this content high level and quick to read, with links to other resources?

**Comment by aornugent** [comment]
Oh, also there's also the predictive deforestation project. @tgoswamy @govarun can provide you with some proposals, presentations and reports to link to.

**Comment by aornugent** [comment]
Here is @waridrox content map.

<img width="1201" alt="screenshot_2021-05-10_at_6 12 33_pm" src="https://user-images.githubusercontent.com/20387761/124834733-97016580-dfc3-11eb-9f80-78e9691bb3ad.png">

**Comment by govarun** [comment]
@sarthakkundra Varun here from the IITK Consulting Group, which is working on the deforestation prediction project. Please ping me when you require the details. Thanks!
