### ISSUE TITLE
Hover Effect in Footer links 

### ISSUE THREAD

**Issue by Palaksharma23** [moja-global/community-website#208]
### Describe the bug.

The links in the footer must have Underline on hovering , Now they just have white color on hover 

### Describe the steps to reproduce the behavior.

1) Go to main Website 
2) Scroll down to footer section
3) Hover on any link 
4) See the effect then 

### Screenshots.

<img width="867" alt="footer" src="https://user-images.githubusercontent.com/87171452/140758173-8809047a-f541-44b9-bfca-eae7201510fa.png">

### Operating Environment

Windows 10 and Chrome Browser

**Comment by its-harsshhh** [comment]
hello, i am interested to work on this issue. so could you please assigned it to me?

**Comment by helper-uttam** [comment]
Hey @Palaksharma23  Is that necessary?  I think this would not look more attractive after putting `text-decoration to underline`.

**Comment by Palaksharma23** [comment]
i think it will help user to find out that it is a redirected link .

**Comment by helper-uttam** [comment]
But as we hover over any link then our cursor will be changed to pointer which shows that there is some link attached to it. 🤔
