### ISSUE TITLE
Case study option in navbar 

### ISSUE THREAD

**Issue by Palaksharma23** [moja-global/community-website#209]
### Describe the bug.

Currently in navbar of the website the option CASE STUDY is little odd 
i think we should make case study option inline with other elements either by decreasing the font-size or by shifting other elements little bit towards left 

### Describe the steps to reproduce the behavior.

1) Go to main website
2) See error in navbar

### Screenshots.

<img width="960" alt="navbar" src="https://user-images.githubusercontent.com/87171452/140761054-52601256-28b4-4793-aa95-34b5d8a0f15d.png">

### Operating Environment

Windows 10 and Chrome Browser

**Comment by yashsehgal** [comment]
Hey maintainers 👋🏽 
I would like to work on this issue if no one is currently working on it.

**Comment by razetime** [comment]
I'm not able to reproduce this on my laptop with the same operating environment you have given. You may need to provide screen resolution/other extensions which might be altering the state of the page.

**Comment by yashsehgal** [comment]
Hey @razetime You can try [Blisk Browser](https://blisk.io/) to test the local rendered page on different screen sizes and fix this accordingly 👍🏽 Hope this might help you.

**Comment by Palaksharma23** [comment]
@yashsehgal currently i am working on this issue , please try on different one.
Thank you

**Comment by Palaksharma23** [comment]
@razetime this issue is present in all sized devices on my laptop.

**Comment by Palaksharma23** [comment]
maybe it is not present on large screens

**Comment by Palaksharma23** [comment]
@sohamsshah @HarshCasper can i work on this issue.

**Comment by Prasanna0908** [comment]
@HarshCasper If nobody is assigned then can I work on this issue?

**Comment by Pravenn18** [comment]
This issue is resolved
