### ISSUE TITLE
Feature Request: Redirect Watch Tutorial to Tutorial page on the Navbar instead of youtube

### ISSUE THREAD

**Issue by Ruchip16** [moja-global/community-website#212]
### Is your feature request related to a problem? Please describe.

After clicking on watch tutorials, it gets redirected to youtube and since we have the tutorial section on the Navbar we can simply redirect watch tutorials to the tutorial page and add the present tutorials there with their youtube links, this wouldn't make the tutorial page look empty 

CC: @HarshCasper 

### Describe the solution you'd like.

![image](https://user-images.githubusercontent.com/72685035/142572927-b2d9d3fc-4069-4b66-84a7-d8c70334b4fc.png)

**Comment by aryanxk02** [comment]
I'll take up this, will do a PR soon! @Ruchip16

**Comment by aryanxk02** [comment]
Actually, I am done doing this and was about to make a PR. I have the file ready! @Ruchip16

**Comment by Ruchip16** [comment]
Okay cool, next time just inform once hence others time wouldn't get wasted but nvm thanks for making the PR @aryanxk02

**Comment by aryanxk02** [comment]
@Ruchip16 Thanks a lot! Will take care hence forth :)
