### ISSUE TITLE
Bug:  Roadmap page

### ISSUE THREAD

**Issue by Sukriti-sood** [moja-global/community-website#216]
### Describe the bug.

- Project Section is breaking the responsiveness of the page
- In Dark Mode View Timeline Option is not readable

### Describe the steps to reproduce the behavior.

Go [here](https://community.moja.global/roadmap)

### Screenshots.

![Roadmap _ Moja G (2)](https://user-images.githubusercontent.com/55010599/142993427-e05bd1da-b064-4571-b8fc-1b4346f148aa.png)

### Operating Environment

Google Chrome

**Comment by nerdynikhil** [comment]
I would like to work on this. @Sukriti-sood
