### ISSUE TITLE
Bug: Sidebar not visible for Screen size: 997px -1280px

### ISSUE THREAD

**Issue by Sukriti-sood** [moja-global/community-website#217]
### Describe the bug.

Sidebar is not visible for Screen size: 997px -1280px and fixx the edit page links in Website, which is currently redirecting to wrong pages.

### Describe the steps to reproduce the behavior.

- Visit [here](https://community.moja.global/).
- From the responsive window, change the screen size between 997px -1280px.

### Expected behavior.

Sidebar should be visible.

### Screenshots.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/55010599/142995779-0809f73d-19b8-4d8e-baf0-562a5bbc945e.gif)

### Operating Environment

Google Chrome

**Comment by Palaksharma23** [comment]
i would love to take up this issue .

**Comment by Sukriti-sood** [comment]
I am working on this.

**Comment by arjunbharti** [comment]
Hey, if this issue is not yet assigned, can I work on it? I am up for fixing it!

**Comment by Palaksharma23** [comment]
@arjunbharti you can go ahead

**Comment by janvi01** [comment]
@Palaksharma23 Can I work on this?

**Comment by Akshit42-hue** [comment]
Can I work on this issue @Sukriti-sood

**Comment by Anbazhagan04** [comment]
Hi, I am Anbazhagan, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you
