### ISSUE TITLE
Improve the Roadmap Page. 

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/community-website#229]
The current state of the roadmap page: 
https://community.moja.global/roadmap
![Screenshot (521)](https://user-images.githubusercontent.com/75530516/145040943-0fe84b41-65ed-45d9-83ba-378ee5ae8b1e.png)

We would like to redesign and improve the current UI. 

One can take inspiration from the following resources:
https://www.asyncapi.com/roadmap
https://docusaurus.io/showcase

**Comment by SanjaySinghRajpoot** [comment]
Yes, it looks a little odd. We can add some sort of pinpoints to mention the projects and some other steps as follow-up chart pattern. 

I would like to collaborate on this issue.

**Comment by SanjaySinghRajpoot** [comment]
I have made the following changes to the roadmap page. @sohamsshah please review these changes.

@padmajabhol please let me know if I can a PR for these changes. 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/67458417/145225438-e9a4754e-bc62-4a3f-8009-a35a9d0878e1.png">

Thank You.

**Comment by sohamsshah** [comment]
> I have made the following changes to the roadmap page. @sohamsshah please review these changes.
> 
> @padmajabhol please let me know if I can a PR for these changes. <img alt="image" width="959" src="https://user-images.githubusercontent.com/67458417/145225438-e9a4754e-bc62-4a3f-8009-a35a9d0878e1.png">
> 
> Thank You.

Hey @SanjaySinghRajpoot , thanks for working on this. Please raise a PR so that we can quickly review and get these changes merged!

**Comment by padmajabhol** [comment]
> I have made the following changes to the roadmap page. @sohamsshah please review these changes.
> 
> @padmajabhol please let me know if I can a PR for these changes. <img alt="image" width="959" src="https://user-images.githubusercontent.com/67458417/145225438-e9a4754e-bc62-4a3f-8009-a35a9d0878e1.png">
> 
> Thank You.

This looks good,

**Comment by padmajabhol** [comment]
> I have made the following changes to the roadmap page. @sohamsshah please review these changes.
> 
> @padmajabhol please let me know if I can a PR for these changes. <img alt="image" width="959" src="https://user-images.githubusercontent.com/67458417/145225438-e9a4754e-bc62-4a3f-8009-a35a9d0878e1.png">
> 
> Thank You.

Sure, please raise a PR for this.

**Comment by SanjaySinghRajpoot** [comment]
@sohamsshah please review these changes.
