### ISSUE TITLE
Bug: Too long navbar list

### ISSUE THREAD

**Issue by Apurba-Nath-cpu** [moja-global/community-website#231]
### Describe the bug.

Currently, the navbar has way too many options which makes it a bit congested. It would make it brief and crisp if we can replace some options with small groupings of them.

### Describe the steps to reproduce the behavior.

1. Go to the community website of Moja Global.
2. View the current navbar.

### Expected behavior.

Insertion of two/three dropdowns to show the current items when hovered or clicked.

### Screenshots.

![Screenshot from 2021-12-09 13-35-41](https://user-images.githubusercontent.com/76649448/145358057-d0bd6fb0-c696-4131-a043-f51840b581e0.png)

### Operating Environment

OS: Ubuntu Linux, Browser: Google Chrome

**Comment by Palaksharma23** [comment]
i would love to take up this issue 
@HarshCasper can you please tell me which options should i add in one dropdown

**Comment by HarshCasper** [comment]
> i would love to take up this issue @HarshCasper can you please tell me which options should i add in one dropdown

You should notice that this issue is already assigned. Since you are a WoC participant, create issues around what is mentioned on your proposal and request for assignment.

**Comment by Palaksharma23** [comment]
sure sir @HarshCasper

**Comment by tanay123456789** [comment]
I am working on it as nobody is active on this issue.

**Comment by Apurba-Nath-cpu** [comment]
The issue is assigned to me and I am working on this isuue right now.

**Comment by tanay123456789** [comment]
okay
