### ISSUE TITLE
The sponsors list is very unresponsive .

### ISSUE THREAD

**Issue by aayushsrivastava9760** [moja-global/community-website#233]
The sponsors list shown at the bottom of the home page is very unresponsive .

![WhatsApp Image 2021-12-11 at 12 16 42](https://user-images.githubusercontent.com/81965095/145667399-f3760f86-43f6-4f2c-85d7-9108d738876a.jpeg)
 
making them more responsive will not only make the website more appealing but will also highlight the sponsors , currently they blend in with the other components and may not be sported by the user .

I want to work on this issue kidly assign it to me .

**Comment by aayushsrivastava9760** [comment]
Kindly assign me this issue , i would like to work on it .

**Comment by sohamsshah** [comment]
Assigned, go ahead!
