### ISSUE TITLE
Upcoming meeting section is showing past meetings 

### ISSUE THREAD

**Issue by Palaksharma23** [moja-global/community-website#236]
### Describe the bug.

![image](https://user-images.githubusercontent.com/87171452/145672717-8366e30f-ef03-4d13-92ca-743198f630cc.png)

### Describe the steps to reproduce the behavior.

Go to https://community.moja.global/initiatives
See error 

### Expected behavior.

I guess these are important meetings or come under other headings so the heading of section should be changed accordingly 

### Operating Environment

Windows 10 and Chrome Browser

**Comment by Palaksharma23** [comment]
@HarshCasper can you please assign this issue to me.

**Comment by sohamsshah** [comment]
Hey @Palaksharma23 , I think the Meeting section currently just has dummy data and so it doesn't make sense what data is present. I guess, we can put the correct data once the #163 is fixed and built. I think we can consider closing this issue at the moment.

Cc: @HarshCasper

**Comment by Palaksharma23** [comment]
okay sir , got it :)
