### ISSUE TITLE
Bug:  ALIGNMENT IN INITIATIVES SECTION 

### ISSUE THREAD

**Issue by reachaadrika** [moja-global/community-website#237]
### Describe the bug.

The alignment of cards in the  /initiatives , looks a bit absurb , to be precise , Google Summer of Docs Card is a bit misaligned . 

### Describe the steps to reproduce the behavior.

Open the /initiatives Page on the community website .

### Expected behavior.

All the cards should be aligned properly , this could be done by shifting the button to bottom , aligned with other buttons .

### Screenshots.

![image](https://user-images.githubusercontent.com/64789514/145674840-a07aae15-0064-456e-b784-10565e34b751.png)

### Operating Environment

Windows 10 , Firebox

**Comment by reachaadrika** [comment]
If this is a valid issue , Can I work on this ?

**Comment by aayushsrivastava9760** [comment]
Just to be sure u meant 'firefox' rt? Also it looks fine on windows 10 , Google Chrome .

**Comment by AayushSaini101** [comment]
Please assign this issue

**Comment by vasantisuthar** [comment]
Is this issue still open?
