### ISSUE TITLE
Revamp Projects section in Roadmap Page 

### ISSUE THREAD

**Issue by sohamsshah** [moja-global/community-website#241]
### Is your feature request related to a problem? Please describe.

Currently, the Projects Section in the Roadmap UI looks something like this.

![image](https://user-images.githubusercontent.com/47717492/145680668-21a674ea-f1f5-4e61-bdbe-c5cb900d6a43.png)

There are couple of minor UI issues that can be seen in the design:
- The horizontal margin between the Projects Cards is more than required. We can improve and keep the content in the center.
- The `View Timeline` CTA button currently looks as an outlier compared to other designs on the page. It should be left-aligned and overall card should have `flex:justify-between` style.
- There is a vertical `Scroll` in the cards. This should be removed and content should be placed accordingly.
- The inner-padding in the Project Cards can be increased to give cleaner look.
- The Modal that opens on clicking the `View Timeline` can be improved in later PRs. This issue focusses solely on the Project Section UI.

### Describe the solution you'd like.

Below is the layout of how cards can restructured (*just* focus on the layout and arrangement. The color, spacing etc. shall be intuitively designed and added based on the project's other implementations)

![image](https://user-images.githubusercontent.com/47717492/145680715-403b2e7d-2a54-43ba-a36e-dcc3d3c9913b.png)

### Describe alternatives you've considered

NA

### Additional context.

This is a sub-issue for #229 . In this the target is to solve the Project Section UI in specific

**Comment by mehabhalodiya** [comment]
Hey, I would like to work on this! Please assign it to me.
Thank you.

**Comment by sohamsshah** [comment]
Sure, thanks! Go ahead @mehabhalodiya !
