### ISSUE TITLE
Newcomers guide 

### ISSUE THREAD

**Issue by Ruchip16** [moja-global/community-website#249]
### Additional context.

Since we have a lot of people contributing to moja-global, a newcomers guide would give them insights on our projects and how can they get started with their contributions 

I have created a doc for the [same](https://docs.google.com/document/d/1a0Hctj1O3CAmCeuPkDacZyFxF-qpApmgxLLmNGDH9qE/edit?usp=sharing )

CC: @HarshCasper @sohamsshah

**Comment by arcadioramos** [comment]
Thank you for this document, I'm very interested in contributing someway and this document helped me so much :)
