### ISSUE TITLE
Bug: the nav bar in iPad pro doesn't work

### ISSUE THREAD

**Issue by iswarmondal** [moja-global/community-website#252]
### Describe the bug.

On the home page, the hamburger icon to toggle the navbar doesn't work properly for iPad pro screen size.
Here is a video demo about the issue

https://user-images.githubusercontent.com/73457704/146355285-c85a4298-8f55-47d6-b61a-e9c96a50452d.mp4

### Expected behavior.

The expected behaviour should be to toggle the navbar from the side as the hamburger icon used to do on mobile screens.

### Operating Environment

I'm using the website in Brave browser which is based on Chromium

### Additional Information

The same issue is presented when the website is viewed on a small laptop screen.

**Comment by arcadioramos** [comment]
Hi, I would like to work on this bug !

**Comment by HarshCasper** [comment]
> Hi, I would like to work on this bug !

Apologies, I assigned @iswarmondal who created this issue. If he is no ready to take it up, I can assign you this issue.

**Comment by arcadioramos** [comment]
Oh, no problem !!!

**Comment by iswarmondal** [comment]
@HarshCasper no problem with that. I'm kinda new to open-source so I might need some help. Thanks for assigning the bug to me.

**Comment by iswarmondal** [comment]
Hay I'm having some trouble with debugging it. Can anyone else take this? @HarshCasper

**Comment by sohamsshah** [comment]
Hey @arcadioramos , you can work on this if @iswarmondal isn't working on this. Please feel free to ping if you face any blockers.

**Comment by iswarmondal** [comment]
Hey! I'm currently busy right now, if anyone wants to work on this issue then go ahead

**Comment by lawanu-tech** [comment]
I would like to work on this issue. Can you assign it to me?

**Comment by HarshCasper** [comment]
Hi @lawanu-tech — I have assigned you this. Let me know if you are planning to work on it.

**Comment by lawanu-tech** [comment]
> Hi @lawanu-tech — I have assigned you this. Let me know if you are planning to work on it.

Thank you. I am going to work on it.

**Comment by ShadyResurrected** [comment]
"Hi, I am Chandradeep Chandra, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you"
