### ISSUE TITLE
Improvise UI for contributors and sponsors sections.

### ISSUE THREAD

**Issue by kushagra487** [moja-global/community-website#255]
I wish to add animation to contributors and sponsors section.

Something similar to a left-right transition.

**Comment by kushagra487** [comment]
Please assign me this issue @padmajabhol

**Comment by padmajabhol** [comment]
Hey @kushagra487 are you still working on this issue?

**Comment by garvitraj** [comment]
Hey i want to work on this issue
could u pls assign it

**Comment by garvitraj** [comment]
Thanks for assigning this issue
will start with this by today

**Comment by garvitraj** [comment]
hey, @padmajabhol I have designed the UI Pls let me know if any changes is required.
cc @HarshCasper 

![Frame 1](https://user-images.githubusercontent.com/62978449/148350155-c5d3d89b-6175-4196-b5d9-fabc53ef8923.png)


Figma File Link :- https://www.figma.com/file/Sms8um8fzQAfMqoSfGi8Bm/moja-global?node-id=2%3A13

**Comment by garvitraj** [comment]
Hey, @padmajabhol i have designed the UI Let me know if any changes is required and where should I commit design files.
![Frame 1](https://user-images.githubusercontent.com/62978449/148350508-e393b89f-b7da-491f-816a-1bbbfc094bfa.png)
