### ISSUE TITLE
Feature Request: Changing the solid color of Roadmap background to a gradient color. 

### ISSUE THREAD

**Issue by SanjaySinghRajpoot** [moja-global/community-website#257]
### Is your feature request related to a problem? Please describe.

Currently, the roadmap banner has a solid colour background that looks too outdated. 

### Describe the solution you'd like.

I have added a new color gradient to the roadmap page. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/67458417/146926850-43229930-0402-4b4f-bed8-77e674779cb5.png">

### Additional context.

I would like to work on this issue.

**Comment by SanjaySinghRajpoot** [comment]
please review this change @sohamsshah

**Comment by padmajabhol** [comment]
@sohamsshah do we need this background change? We are trying to have consistency throughout the website.

**Comment by sohamsshah** [comment]
I think this would violate the colorscheme of the design of the website. Closing this
