### ISSUE TITLE
Feature Request: Add scroll to top button

### ISSUE THREAD

**Issue by 7ORP3DO** [moja-global/community-website#258]
### Is your feature request related to a problem? Please describe.

When the page is really long, it becomes too tedious to scroll back to top through screens and screens of content. Hence the role of the Scroll to top button.

**Comment by sohamsshah** [comment]
Hey @7ORP3DO, are you working on this?

**Comment by 7ORP3DO** [comment]
Hi @sohamsshah, For some reason now I am not working on this issue.  I apologize for that .🙇 

 **You can assign it to someone else**

**Comment by tejaswari7** [comment]
I'm beginner to this project
I would like to take this issue

**Comment by tejaswari7** [comment]
should the scroll button exists on all the pages of website?

**Comment by padmajabhol** [comment]
> should the scroll button exists on all the pages of website?

Ideally, yes.

**Comment by tejaswari7** [comment]
I'm getting this error when I run the command `git clone git@github.com:<USERNAME>/community-website.git && cd community-website`

<img width="465" alt="image" src="https://user-images.githubusercontent.com/55801723/149156837-bec84e20-eda1-4571-8c9e-21b91d800566.png">

**Comment by 7ORP3DO** [comment]
> 
I am also getting the same error. Alternatively you can use this command : 
```sh
git clone https://github.com/tejaswari7/community-website.git
```

**Comment by tejaswari7** [comment]
I went through documentation of docusaurus and found that they removed scrollToTop feature
[Removed fields](https://docusaurus.io/docs/migration/manual#removed-fields)
![image](https://user-images.githubusercontent.com/55801723/151036617-6ba147c7-f18f-4a37-a4c7-86ec783bf2b7.png)

can the feature be added using reactjs if yes, then I'm confused how should I procced.
Any Suggestions??

**Comment by padmajabhol** [comment]
> I went through documentation of docusaurus and found that they removed scrollToTop feature [Removed fields](https://docusaurus.io/docs/migration/manual#removed-fields) ![image](https://user-images.githubusercontent.com/55801723/151036617-6ba147c7-f18f-4a37-a4c7-86ec783bf2b7.png)
> 
> can the feature be added using reactjs if yes, then I'm confused how should I procced. Any Suggestions??

You can use react hooks to easily implement this. Docusaurus is built on top of react so you can pretty much do everything that you could have done in a react project. For this particular feature, use the useState and useEffect hooks to change the state on a particular condition. For smooth scrolling, use the window object.

**Comment by romasinha** [comment]
@padmajabhol I have raised a PR solving this issue the same way as you've mentioned i.e using React Hooks and the window object.

**Comment by padmajabhol** [comment]
> @padmajabhol I have raised a PR solving this issue the same way as you've mentioned i.e using React Hooks and the window object.

Thank you for contributing, I'll review it soon. Though let us know when you are working on an issue before raising a PR, as it might cause confusion to other developers.

**Comment by romasinha** [comment]
Yes, my bad. I will keep that in mind.

**Comment by ShadyResurrected** [comment]
Hi, I am Chandradeep Chandra, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you
