### ISSUE TITLE
Alignment Center for Project Title for a better UI

### ISSUE THREAD

**Issue by Prasanna0908** [moja-global/community-website#269]
Currently, the project title of the roadmap section is left aligned 
![Left aligned](https://user-images.githubusercontent.com/65851817/148341001-af00023a-23a6-4d47-ab38-4035023608b0.PNG)
<br /><br />
It would be better if it was aligned as center
![Center Aligned](https://user-images.githubusercontent.com/65851817/148341216-bd316be1-e234-47e7-9e10-39458e1d2032.PNG)
<br /><br />
Responsive UI :
![Center Aligned Responsive](https://user-images.githubusercontent.com/65851817/148341782-b35769c9-21c4-4cf7-92f1-ed092f279c77.PNG)
<br /><br />

**Comment by Prasanna0908** [comment]
Can someone assign me this issue?

**Comment by kitarp29** [comment]
Hey @Prasanna0908 
Are you still working on this?
I can get this done.
@eemike07 If you could assign it to me.

**Comment by eemike07** [comment]
I don't have assign privileges. I'm just a contributor :(

**Comment by Pravenn18** [comment]
Hey i have solved this issue #277, please close this issue

**Comment by Pravenn18** [comment]
i have solved this issue #277 please review it and close this issue
