### ISSUE TITLE
Add Vercel banner in the Readme under a Sponsors category

### ISSUE THREAD

**Issue by sarthakkundra** [moja-global/community-website#28]
The SVG file can be found in the `images` directory inside `static` directory. By the name of `powered-by-vercel.svg`

**Comment by soumik2012** [comment]
@sarthakkundra can I work on this

**Comment by sarthakkundra** [comment]
@soumik2012 Sure! Go for it.

**Comment by sarthakkundra** [comment]
@soumik2012 You can find the image in this PR [PR](https://github.com/moja-global/contributor-website-v2/pull/27)

**Comment by soumik2012** [comment]
@sarthakkundra I can add this deploy button at the end of the readme. a file like this ...
![image](https://user-images.githubusercontent.com/66599363/125751175-a2902af3-9df3-423b-8c44-7a0d5a1610f9.png)
what you say ??

**Comment by soumik2012** [comment]
@sarthakkundra image in not in `static`  directory

**Comment by sarthakkundra** [comment]
> @sarthakkundra image is not in `static` directory

Please read the comment above this.

**Comment by sarthakkundra** [comment]
> @sarthakkundra I can add this deploy button at the end of the readme. a file like this ...
> ![image](https://user-images.githubusercontent.com/66599363/125751175-a2902af3-9df3-423b-8c44-7a0d5a1610f9.png)
> what you say ??

Add a `Sponsors` section above `Getting Involved` section and add the banner inside that section.

**Comment by soumik2012** [comment]
> > @sarthakkundra image is not in `static` directory
> 
> Please read the comment above this.

![image](https://user-images.githubusercontent.com/66599363/125774174-77b15753-f6d8-44da-b8b1-a3294faa48bc.png)
see @sarthakkundra there is no `powered-by-vercel.svg`

**Comment by soumik2012** [comment]
> > > @sarthakkundra image is not in `static` directory
> > 
> > 
> > Please read the comment above this.
> 
> ![image](https://user-images.githubusercontent.com/66599363/125774174-77b15753-f6d8-44da-b8b1-a3294faa48bc.png)
> see @sarthakkundra there is no `powered-by-vercel.svg` actually your PR #27 does not merge yet you have added the IMG in your in the PR #27 maybe. that's why i can't see.

@sarthakkundra

**Comment by sarthakkundra** [comment]
@soumik2012 Thanks for your interest. This issue has been fixed by #30 .
