### ISSUE TITLE
Feature Request: Willing to contribute and work on a sponsor page

### ISSUE THREAD

**Issue by niloysikdar** [moja-global/community-website#288]
### Is your feature request related to a problem? Please describe.

Hi, I am a new and first-time contributor for Moja Global. I want to contribute to the projects under Moja Global, probably I can start by fixing the design and code of some of the sponsors' pages.

### Additional context.

cc @HarshCasper

**Comment by padmajabhol** [comment]
Hey @niloysikdar , could you please elaborate a little more on what you want to work on, maybe a few screenshots could work. Thanks.

**Comment by crystal-kishore** [comment]
Can i resolve this issue
