### ISSUE TITLE
[UI] : Misaligned content in initiative page in mobile view

### ISSUE THREAD

**Issue by ghulamyazdani** [moja-global/community-website#295]
### Describe the bug.

On the initiative page, contents are misaligned as shown below pic.
![image](https://user-images.githubusercontent.com/55938346/152808583-28658bf4-ce92-42de-8c53-ced789448445.png)

![image](https://user-images.githubusercontent.com/55938346/152808711-2f7ea2d2-66ed-4a19-ae6f-a662f46ad9a3.png)

### Describe the steps to reproduce the behavior.

Go on to the https://community.moja.global/initiatives page and scroll down to our meeting while being in mobile view,
You could see the content misaligned there.

### Expected behavior.

The content should be aligned perfectly so that it would look good in mobile view.
![image](https://user-images.githubusercontent.com/55938346/152809735-7bf631f5-f1ba-4777-8e1e-0f629b9d5fd0.png)

### Operating Environment

Chrome

**Comment by ghulamyazdani** [comment]
I would like to work on this issue.

**Comment by sohamsshah** [comment]
Hi @ghulamyazdani , currently this section is being tackled in #272 where we are replacing the Meetings Section with the Calendar. Feel free to work on other issue or raise new issue. Thanks.
