### ISSUE TITLE
Documentation: Contributor guidelines 

### ISSUE THREAD

**Issue by Ash-KODES** [moja-global/community-website#308]
### What is the current documentation state?

Dont have a contributor guidelines of MOJA-GLOBAL

**Comment by Ayan-thecodeking** [comment]
Hi, I am Ayan Gupta , a contributor to OpenForce 2022. I would like to work on this issue let me know is there is any  changes required . I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by ritikalohia** [comment]
@Ash-KODES , I want to know more about this issue much more. How this should be made and what is the process? doubts are:
1. Should we make a whole documentation for every repo and tell what it is, and how does it function?
2.  Or in these guidelines, we will tell them that what you should do or should not do while contributing?
3. Or guidelines tell them about community website and help contributor to understand the code?
