### ISSUE TITLE
Feature Request: Add social media share icons for blog articles

### ISSUE THREAD

**Issue by indraantoor** [moja-global/community-website#315]
### Is your feature request related to a problem? Please describe.

Currently there is no **share button** on the blog. If the user has to share an **article** on **any social media platform** they would have to copy the link and paste to share it. That does work, but for blogs it will be a good practice to add share icons so that user can **click** on the **icon** of the social platform on which they want to share that article and can share it. 

### Describe the solution you'd like.

I am thinking of social icons like these, which when you hover on it will also display the text "share".
![share icons](https://user-images.githubusercontent.com/64259328/157825076-acdbd63b-a17d-464d-9894-25b98880cb02.png)

Article on blog page currently looks like this:
![blog page](https://user-images.githubusercontent.com/64259328/157825398-588925e0-e5ab-4d69-b56a-d25b1eff47cc.png)

I am thinking of placing the social icons like those under the heading. 

### Additional context.

I would love to contribute to the project under Codeflow **Openforce 2022**.
Kindly assign me this issue. It would be great!

**Comment by indraantoor** [comment]
Kindly assign me this issue under Codeflow Openforce 2022.

**Comment by varsha089** [comment]
Hi, I am Varsha, a contributor to OpenForce 2022. I would like to contribute to this issue. Could you please assign it to me.

**Comment by anubhav2102** [comment]
Please assign this issue to me, i have previously solved similar issue in a project.

**Comment by Shreyash1601** [comment]
Hey I am Shreyash participant of openforce 2022. Kindly assign this issue to me

**Comment by PrabhuRaamDev** [comment]
Hi, I am Prabhu raam, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue.

**Comment by jigarvyasidea** [comment]
Hi, I am Jigar Vyas, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue.

**Comment by tanay123456789** [comment]
working on it.
