### ISSUE TITLE
Bug: Clicking on Edit this page redirects to 404 error page 

### ISSUE THREAD

**Issue by Palaksharma23** [moja-global/community-website#317]
### Describe the bug.

When clicking on Edit this page it should redirect to the correct page, it shows a 404 error page

### Describe the steps to reproduce the behavior.

1. Go to any blog post on mojaglobal Community Website
2. Click on edit this page 
 

### Expected behavior.

It should redirect to the correct page 

### Screenshots.

https://user-images.githubusercontent.com/87171452/159173648-5d8252d2-a971-4818-9420-e22c168fbe3f.mp4

### Operating Environment

Windows 10 and Chrome Browser

**Comment by tanay123456789** [comment]
working on it

**Comment by ritikalohia** [comment]
@Palaksharma23 , I have gone through this issue. when we click on 'edit this page', it will redirect to 404 error page. I have tried something. but I have some doubt. it must be redirected  to md file link like " https://github.com/moja-global/community-website/edit/main/website/blog/2021-11-29-meet-moja-global-outreachy-interns.md " . I have done this thing, like if we click on edit this page. it will redirect to the above type of link. if this solution is ok, then I will make a PR.

**Comment by tanay123456789** [comment]
@ritikalohia  I have already open a PR for same som pls go and find other issues to work on.

**Comment by ritikalohia** [comment]
ok @tanay123456789
