### ISSUE TITLE
Feature Request: The "know more" element of the navbar doesnt show the green transition while rest all elements show !

### ISSUE THREAD

**Issue by siddhi-244** [moja-global/community-website#319]
### Is your feature request related to a problem? Please describe.

The "know more" element of the navbar doesnt show the green transition while rest all elements show !

### Describe the solution you'd like.

I would like to add that green transition effect to know more element as well

**Comment by siddhi-244** [comment]
i would like to work on this issue

**Comment by padmajabhol** [comment]
I believe that's because it's not a link but just a drop-down button.
