### ISSUE TITLE
Feature Request: A small change in website in mobile view! 

### ISSUE THREAD

**Issue by siddhi-244** [moja-global/community-website#320]
### Is your feature request related to a problem? Please describe.

![Screenshot (170)](https://user-images.githubusercontent.com/69195262/160224659-2752b235-7441-4f5b-bf89-0e9d50c53943.png)

The box width need to be increased

### Describe the solution you'd like.

I would try to increase the width !

### Additional context.
I am participating in Gsoc this year and would love to contribute to this project

**Comment by siddhi-244** [comment]
i would like to work on this issue !

**Comment by meghagangadhar13** [comment]
I would like to work on this issue

**Comment by siddhi-244** [comment]
@chicken-biryani can I work on this issue.

**Comment by chicken-biryani** [comment]
@siddhi-244 yes please.

@meghagangadhar13 issues usually take place on a first come first serve basis. Since Siddhi created it and commented before you did... By default she gets to work on.

Feel free to create/try new issues.
