### ISSUE TITLE
Bug: Icons not visible in light mode 

### ISSUE THREAD

**Issue by Palaksharma23** [moja-global/community-website#328]
### Describe the bug.

The color of icons on https://community.moja.global/roadmap is visible in dark mode only. 
![image](https://user-images.githubusercontent.com/87171452/165465277-7e5661fd-6d6d-4bbd-b757-f13d9f4c6f4c.png)
![image](https://user-images.githubusercontent.com/87171452/165465285-cf01e574-1a4e-4ce4-adb9-95bd13898e38.png)

### Describe the steps to reproduce the behavior.

1) Go to https://community.moja.global/roadmap
2) Toggle in light mode 
![image](https://user-images.githubusercontent.com/87171452/165464777-94329b08-0cfc-40ea-84cf-76cf82389c9f.png)
3)Toggle in Dark mode 
![image](https://user-images.githubusercontent.com/87171452/165464832-25874f9e-2b28-49f7-9f92-1968278883e9.png)

Take your pointer on the position of icons and it will get changed to hand which means icons are there just the color is same as background color 

### Operating Environment

Windows 10 and Chrome Browser

**Comment by Saurabh-Suchak** [comment]
Hey, I'd like to work on this. @shubhamkarande13 can you assign this to me?

**Comment by padmajabhol** [comment]
Any updates on this? @Saurabh-Suchak

**Comment by Saurabh-Suchak** [comment]
@padmajabhol will be done by tomorrow.

**Comment by ORKO06** [comment]
@HarshCasper @padmajabhol 

Can I work on this issue?

**Comment by ayush78781** [comment]
## Dark Mode
<img width="957" alt="image" src="https://user-images.githubusercontent.com/76848435/172240341-d98ec992-adef-424c-9536-0d092ef90a0e.png"><br>
## Light Mode
<img width="957" alt="image" src="https://user-images.githubusercontent.com/76848435/172240428-d8ef3781-e37a-4253-9def-7d47c2b74ff2.png">

Hey! @HarshCasper I worked on this issue. Please have a look, if everything looks good I will raise a pr to it.

**Comment by padmajabhol** [comment]
> @HarshCasper @padmajabhol
> 
> Can I work on this issue?

Hi, this issue has already been assigned, I'll let you know when we have more issues.

**Comment by padmajabhol** [comment]
> ## Dark Mode
> <img alt="image" width="957" src="https://user-images.githubusercontent.com/76848435/172240341-d98ec992-adef-424c-9536-0d092ef90a0e.png">
> 
> ## Light Mode
> <img alt="image" width="957" src="https://user-images.githubusercontent.com/76848435/172240428-d8ef3781-e37a-4253-9def-7d47c2b74ff2.png">
> 
> Hey! @HarshCasper I worked on this issue. Please have a look, if everything looks good I will raise a pr to it.

Let me check with @Saurabh-Suchak, if there has been no progress from his side, we will go with this. Though this looks good I could always recommend you to let us know before you proceed to work on something.

**Comment by padmajabhol** [comment]
Hi @ayush78781 , I have assigned you to this issue.

**Comment by ayush78781** [comment]
Hey @padmajabhol please review the pull request I raised.
