### ISSUE TITLE
Revamp community website

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/community-website#334]
We are coming up with the second iteration of the community website with major UI changes. 
For now, we are planning to change the landing page which also includes the know the community, and the sponsorship section. You can find the Figma link attached [here](https://www.figma.com/file/cpR8K7fBhznhMB70Ym3Ui3/community-website).
We are open to suggestions to improve the current prototype. 
We are looking for two volunteers(preferably from React background) to help us with the development. Please note that you will be sending your pull requests to the [community-website.v2](https://github.com/moja-global/community-website/tree/community-website.v2) branch.

**Comment by Aditya-Jha2002** [comment]
I would like to work on this.

**Comment by padmajabhol** [comment]
Hi @Aditya-Jha2002 a few people had reached out to me, give me a day to confirm if they still want to work on this, if not I'll assign you.

**Comment by ishitaac** [comment]
Interested to work on this issue!

**Comment by arishmaurya** [comment]
@padmajabhol  i am interested to work on  this feature.  I have prior  experience in react js and also contributed in gssoc . I would love to work and collaborate on this issue

**Comment by disha1202** [comment]
I would like to work on this issue.

**Comment by padmajabhol** [comment]
@ishitaac you can help us with coming up with a light and dark theme for the proposed prototype and maybe later design the rest of the pages with me?
I'm assigning @disha1202 to work with @ORKO06 to help us develop the second iteration. 
@arishmaurya the other two people had reached out to us on our slack so I decided to go with them. You can surely look for other issues that might interest you.

**Comment by arishmaurya** [comment]
@ayush78781  I'm ready to work on this can you please assign it to me
