### ISSUE TITLE
PSF - FLINT Visualization tool

### ISSUE THREAD

**Issue by sarthakkundra** [moja-global/community-website#34]
Write documentation about FLINT Visualization tool under the projects section. Refer to this [section](https://docusaurus.io/docs/docs-introduction) to understand how to create a documentation page and how to add it to the sidebar. Feel free to discuss or submit draft proposals here.

The documentation should include the following sections:- 

- [ ] About the project.
- [ ] Use cases of the project.
- [ ] Learning resources (References to blogs, moodle, videos, etc.)

Refer to this [Google Doc](https://docs.google.com/document/d/1x1M7vSvRvyqrUfrfkfS6b1bpIYy3jHgpBEHE_W4bsSQ/edit?usp=sharing) for more information.

**Comment by Aman1905** [comment]
Hey I am interested to work on this issue. Can you assign it to me? @sarthakkundra

**Comment by sarthakkundra** [comment]
Hey @Aman1905 done! 😄 . Feel free to discuss your doubts or blockers in this thread. Cheers!

**Comment by Aman1905** [comment]
Hey firstly sorry for not being available for long time since my college exams were going on but can you help me that what should I put in the Learning Resources section of the blog

**Comment by sarthakkundra** [comment]
@aornugent can we get a moodle link to the resources? For the learning resources as mentioned by @Aman1905

**Comment by aornugent** [comment]
I'm not sure our Moodle course has launched yet. Tagging @ksocksTR33Z in case he knows more? 🤞

**Comment by ksocksTR33Z** [comment]
Guy had left it unpublished previously I believe. It may be as simple as asking him for the admin info to help launch it.

**Comment by Aman1905** [comment]
So any other (blog, video etc) more resources about this taswira software. It may help me for creating documentation more nicely.
