### ISSUE TITLE
Bug: Make Hero Section on the landing page responsive for smaller screens

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/community-website#344]
### Describe the bug.

Currently we don't have css that could make the hero section look better in smaller screens.
You need to switch to [this branch](https://github.com/moja-global/community-website/tree/community-website.v2l) to this page.

### Expected behavior.

Center all elements and hide the logo for screensize < 1350px.

### Screenshots
![Screenshot from 2022-07-22 22-37-02](https://user-images.githubusercontent.com/75530516/180490387-9a22c8b8-5a84-447c-9cf0-fee71c37ea12.png)
.

### Operating Environment

Linux Ubuntu

**Comment by Mr-Georgie** [comment]
I'm on it 🙏

**Comment by padmajabhol** [comment]
> I'm on it pray

Thanks a lot!

**Comment by rohinish404** [comment]
i'd like to work on this is the issue is still there. Let me know.

**Comment by Mr-Georgie** [comment]
Hi rohinish404, I have done it. 

Making pull request now

**Comment by 03amir** [comment]
@padmajabhol  can i work on this issue?

**Comment by padmajabhol** [comment]
Hi @03amir this has already been assigned, please watch out for other issues, thanks for reaching out!
