### ISSUE TITLE
PSF - FLINT Reporting Tool

### ISSUE THREAD

**Issue by sarthakkundra** [moja-global/community-website#35]
Write documentation about FLINT Reporting tool under the projects section. Refer to this [section](https://docusaurus.io/docs/docs-introduction) to understand how to create a documentation page and how to add it to the sidebar. Feel free to discuss or submit draft proposals here.

The documentation should include the following sections:- 

- [ ] About the project.
- [ ] Use cases of the project.
- [ ] Learning resources (References to blogs, moodle, videos, etc.)

Refer to this [Google Doc](https://docs.google.com/document/d/1x1M7vSvRvyqrUfrfkfS6b1bpIYy3jHgpBEHE_W4bsSQ/edit?usp=sharing) for more information.

**Comment by raghavraj-27** [comment]
Can I work on this @sarthakkundra

**Comment by alokprinc** [comment]
its my first issue and i would like give my best on this issue.
allow me to work on this one.

**Comment by shivani6320** [comment]
I would like to work on this issue as an outreachy applicant. @sarthakkundra @HarshCasper Can you please assign me this issue?
