### ISSUE TITLE
Feature Request: revamp "Know the community" section

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/community-website#351]
### Describe the solution you'd like.

We are changing the current "Know the community" section of our website.
Please refer to the below image for the reference.

![MacBook Pro 14_ - 2](https://user-images.githubusercontent.com/75530516/185790235-377b1089-a77e-4ffd-a07b-1ec0723fdbad.png)

If are interested to work on this, we might additionally want you to attend our community meetings.
Its recommended that you accomplish this in multiple commits, and open a PR right after the first one.

**Comment by harshilhuda** [comment]
I would like to work on this

**Comment by janvi01** [comment]
I would like to work on this.

**Comment by harshilhuda** [comment]
What should the animation be like when the arrows are pressed ? @padmajabhol

**Comment by rahulsh18** [comment]
hey, i'd like to work on this

**Comment by samyakshah3008** [comment]
Hey Team, I would love to work on this feature. Tech stack seems right fit for me. 
Can you please assign me this issue?

**Comment by padmajabhol** [comment]
@samyakshah3008 please go ahead!

**Comment by samyakshah3008** [comment]
I am working on it, updated with Padmajha via DM.

**Comment by samyakshah3008** [comment]
Hey @padmajabhol 👋  

I have completed the screen for this task, but I am yet to add in our codebase. 
I have created a separate repo and hosted the screen. 

Live link: https://frabjous-dragon-836472.netlify.app/ 
Source code: https://github.com/samyakshah3008/moja-global-community-screen 

P.S. I am yet to refactor my code, please look about the milestones.

For carousel in cards, I have used **Better React Carousel** library ⬇️ 
Reference: https://reactjsexample.com/react-responsive-carousel-component-with-grid-layout-to-easily-create-a-carousel-like-photo-gallery/ 

Please check the live link and let me know if there are any changes you want to make. 

Note: I'll add background color as mentioned in style guide when I'll do my final touch.

**Comment by HarshCasper** [comment]
Hi @samyakshah3008 — That's great work. Can you please go ahead and create a PR?

**Comment by samyakshah3008** [comment]
Sure @HarshCasper 😄 
Thanks a lot for reviewing!

**Comment by samyakshah3008** [comment]
Created PR and working on the requested changes! 
Talked to reviewers for the same, and will complete the requested changes as soon as possible.
