### ISSUE TITLE
Feature Request: revamp Sponsors section

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/community-website#352]
### Describe the solution you'd like.

![MacBook Pro 14_ - 5](https://user-images.githubusercontent.com/75530516/185790512-41270b3b-9ac4-4d68-9b7c-cf9fc395d110.png)

We are changing the current sponsors section of our website.
Please refer to the below image for the reference.

Functionality: every time a user clicks on a particular sponsor, the content on the right side changes. 

If are interested to work on this, we might additionally want you to attend our community meetings.

**Comment by rahulsh18** [comment]
i'd like to work on this

**Comment by Debarshi95** [comment]
Hi @padmajabhol , I would like to work on this. Can you please assign me?

**Comment by legendarykamal** [comment]
hey @padmajabhol is there any figma file for the design that you have taken ss?
