### ISSUE TITLE
Bug:  remove link underline from hero sectio buttons

### ISSUE THREAD

**Issue by padmajabhol** [moja-global/community-website#354]
### Describe the bug.

You can view underline in buttons when you click on them which is visually undesirable.

### Expected behavior.

There should be no text underline when someone clicks on the link.

### Operating Environment

macOS 12.5

**Comment by codewarsfx** [comment]
hi, id love to work on this

**Comment by Vedant-Manjrekar** [comment]
Hey, if this issue is not ressolved I would like to work on this.

**Comment by codewarsfx** [comment]
oh it is @Vedant-Manjrekar ...already on it

**Comment by padmajabhol** [comment]
any updates on this? @codewarsfx

**Comment by MukulKolpe** [comment]
Hey, If no one is working on this issue right now, can I pick this one?

**Comment by padmajabhol** [comment]
> @padmajabhol I can't seem to replicate the bug talked about in this issue. The hero section buttons have no underlines on my served page ..has it been resolved?

You need to pull the community.website.v2 branch instead of main.

**Comment by codewarsfx** [comment]
oh thanks @padmajabhol
