### ISSUE TITLE
Bug: Website's language not changing.

### ISSUE THREAD

**Issue by Vedant-Manjrekar** [moja-global/community-website#355]
## Website's language is not changing when language other than English is chosen.

Currently there are 2 options English and Spanish (̄Espanol) , but when clicked on Spanish language the language doesn't change.

### Operating Environment

MacOs

**Comment by legendarykamal** [comment]
Hi, I would like to work on fixing this.

**Comment by padmajabhol** [comment]
Hi, if you think you can help us with the translation, please consider approaching one section at a time.

**Comment by legendarykamal** [comment]
Yes, I will make issues for different section and then go on with one by one 👍
