### ISSUE TITLE
Documentation: There is no GitHub Workflow

### ISSUE THREAD

**Issue by ItsRoy69** [moja-global/community-website#358]
### What is the current documentation state?

When you are clicking the "Github Workflow" under "Know the Community" section in https://community.moja.global/ you'll find it gets redirected to https://docs.moja.global/en/latest/DeveloperWorkflow/index.html which shows no documentation

### Where is this stated?

It is stated here -https://docs.moja.global/en/latest/DeveloperWorkflow/index.html

![2022-08-25 (1)](https://user-images.githubusercontent.com/78967360/186597403-b36f3e74-f2b6-44ac-97bd-76cad7cf1330.png)

### Why do you want to improve the statement?

For having a look at the workflow

### Proposed Statement

Make a workflow inside https://docs.moja.global/en/latest/DeveloperWorkflow/index.html

**Comment by legendarykamal** [comment]
hi @ItsRoy69 thankyou for opening the issue , I have linked a PR which will solve this issue :smiley:
