### ISSUE TITLE
PSF - Predictive Deforestation Project

### ISSUE THREAD

**Issue by sarthakkundra** [moja-global/community-website#36]
Write documentation about FLINT Deforestation Project under the projects section. Refer to this [section](https://docusaurus.io/docs/docs-introduction) to understand how to create a documentation page and how to add it to the sidebar. Feel free to discuss or submit draft proposals here.

The documentation should include the following sections:- 

- [ ] About the project.
- [ ] Use cases of the project.
- [ ] Learning resources (References to blogs, moodle, videos, etc.)

Refer to this [Google Doc](https://docs.google.com/document/d/1x1M7vSvRvyqrUfrfkfS6b1bpIYy3jHgpBEHE_W4bsSQ/edit?usp=sharing) for more information.

**Comment by Mukulikaa** [comment]
Hi, I would like to take up this issue!

**Comment by sarthakkundra** [comment]
Go ahead @Mukulikaa. If you need any help regarding the project and/or it's content. I think @govarun can help you.

**Comment by aornugent** [comment]
@tgoswamy @govarun - please provide a link to your proposals, reports and results. Secondly, we'll need instructions for how new users can get started with this projects.

@Mukulikaa - take a look at the #deforestation-algorithm channel on Slack and include a link to the Linux Foundation project page: https://mentorship.lfx.linuxfoundation.org/project/926665ac-9b96-45aa-bb11-5d99096be870

**Comment by Mukulikaa** [comment]
Thank you for being patient @sarthakkundra; I know I'm taking my own sweet time with it 🙂. Hopefully I'll be done within the week.

**Comment by Mukulikaa** [comment]
Hey @King-kay, unfortunately this has fallen off my radar completely and I don't think I'll be able to get back to it in the near future. If you want to work on it, you are welcome to! Thanks.

**Comment by King-kay** [comment]
Okay...thanks @Mukulikaa , Secondly, i'll need instructions/insights for how new users can get started with this project. 
I would like to take up this issue
