### ISSUE TITLE
CSF - Community Specific Documentation

### ISSUE THREAD

**Issue by sarthakkundra** [moja-global/community-website#37]
We plan to add documentation for our community as well. Something along the lines of how [Rust lang](https://www.rust-lang.org/community) does it. We plan to add details about how we work, the different ways to get involved, meeting plans, how to access previous meetings' minutes, recordings, etc.

Please refer to this [link](https://docusaurus.io/docs/docs-introduction) on how to add sections in the docs section and adding items into the sidebar.

Let's start by adding the different groups that we have like 

- [ ] Documentation Working Group
- [ ] Technical Steering Committee
- [ ] etc.

**Comment by raghavraj-27** [comment]
Hey @sarthakkundra .. I would like to work on this.

**Comment by Siddhant-K-code** [comment]
I can work on this issue. My Approach for this will be : 

- First will try to Give all pointers about getting involved ( various tech stack projects and community website - docs. ) that you and harsh gave in recent meetings ( can be taken from the Presentation ) 
- Slack Channel Invite/Details for Communication
- Drive Links of Recent Meetings.

**Comment by sarthakkundra** [comment]
Hey @Siddhant-K-code. Thanks for showing interest. Your approach looks interesting! Some pointers on the same:-

1. Let's create a component for rendering the meeting minutes and maybe take the titles from [here](https://github.com/moja-global/Google.Season.of.Documentation/tree/master/meeting-minutes). We can use the Github API for this or a custom webhook.
2. Don't worry about the Slack invite as they are already in the footer which is on every page.
3. Drive link of recent meetings sounds good. But again use a component to render their dates/names nicely. 
 
You should make a Higher Order Component for this and use it for both meeting minutes and video links. Assigning the issue to you. Feel free to ask your doubts or discuss your blockers in this thread. Cheers! 😄

**Comment by Siddhant-K-code** [comment]
What should be the naming in NavBar for that? 

`Projects`     `Blogs`    `????`

**Comment by sarthakkundra** [comment]
Will need to think a bit more about that before approving anything. As of now I'm planning the roadmap to be there.

**Comment by Siddhant-K-code** [comment]
> Will need to think a bit more about that before approving anything. As of now, I'm planning the roadmap to be there.

I am also planning to create a small architecture tree for that, it will be easy to discuss things, maybe in our Tuesday sprint.

**Comment by Siddhant-K-code** [comment]
@sarthakkundra Any Update on Roadmap?
