### ISSUE TITLE
Bug: Slack link in the footer.

### ISSUE THREAD

**Issue by aniketnegii** [moja-global/community-website#370]
### Describe the bug.

The link to join the slack is 'Sign In' those who have not joined the workspace are not able to join.
The link should be an invite link such that new people can join the slack workspace.
![image](https://user-images.githubusercontent.com/60145485/193731125-ef33ffa7-bcb2-4e46-ba23-1f510a4bc7b0.png)

### Operating Environment

Windows 10

**Comment by padmajabhol** [comment]
Could you elaborate a bit more? From what I see, its working exactly how we wish it to be.

**Comment by aniketnegii** [comment]
To replicate the issue please try to log in using a new email/account of slack.
If you don't face an issue I believe it was only for my account.
For reference, I was getting this error. 
![Slack Issue](https://user-images.githubusercontent.com/60145485/193981761-75a66bb0-7dd6-4d1b-bb91-d2eb81fd3f49.jpeg)

**Comment by RUCHI21CODES** [comment]
Can you please assign me this issue, I feel like I might help because I have the knowledge of CSS, HTML, JS and I might be able to solve this

**Comment by samyakshah3008** [comment]
Hey team, I would love to work on this, can you please assign me this issue?
