### ISSUE TITLE
Feature Request: Update Website UI

### ISSUE THREAD

**Issue by AM1CODES** [moja-global/community-website#371]
### Is your feature request related to a problem? Please describe.

The current community website looks really well made. It has possibly all the things that the org wants to display but i was wondering if we could work on upgrading the look a little bit. Again, the website looks great and does the job but we can always play around and update the visual appearance a bit.

### Describe the solution you'd like.

I would like to give it a shot and try and upgrade the look of the website(maybe even work around improving a bit of UX - minimising scrolls, better navigation and so on.) Work on the look of the community website and do my best to contribute as a Product Designer and contribute to the Moja Global community.

**Comment by PriteshKiri** [comment]
Hey!
There are few small UI changes I found can improve the current design.
1. Need to center align the hero text on mobile screens
2. Need to increase the image size of the "Engage with the Community" section on mobile screens
3. Need to reduce padding for the "Contributors" section on mobile screens
4. We can add a drop shadow effect to the image of the "Engage with the Community" section
