### ISSUE TITLE
Bug: Demo Days button in light theme

### ISSUE THREAD

**Issue by samyakshah3008** [moja-global/community-website#373]
### Describe the bug.

In the header section of our community website, **Demo Days** button's **text** is not visible when we **hover** on it in light mode/theme. 
Also **without hover** of button, the text is not clearly visible.

## Effect on Hover of button demo days
- I'll change the color of button's text to white.
- Or if there is a specific style guide or design, I'll implement accordingly. 
## Effect without Hover of button demo days
- I'll change the text's color of button to green so as user can clearly see. 
- Or if there is a specific style guide or design, I'll implement accordingly. 

### Expected behavior.

# Without Hover: 
![image](https://user-images.githubusercontent.com/86982322/202000025-5788f208-0e31-42ce-be4f-eebc9cd5df82.png)

# With Hover: 
![image](https://user-images.githubusercontent.com/86982322/202000125-d727f031-da99-41c0-b4c6-d3061a998144.png)

### Screenshots.

# Bug Without Hover (Text is not clearly visible)
![image](https://user-images.githubusercontent.com/86982322/202001409-f731c142-68e1-4dfe-ad13-faaf09804c5a.png)

# Bug with Hover (Text is not visible)
![image](https://user-images.githubusercontent.com/86982322/202001605-100379a8-3257-4daa-b19e-755fb3355b65.png)

### Operating Environment

Windows 11, OS Build: 22000.1219 and Version: 21H2

**Comment by samyakshah3008** [comment]
I would love to work on this issue and fix it.

**Comment by Shruti799** [comment]
Hello! Can I work on this issue?

**Comment by ARYA-RAY** [comment]
could u assign me this issue?

**Comment by Shruti799** [comment]
I will work on this issue.

**Comment by ksba2004** [comment]
I would like to work on this issue. Please assign this to me @samyakshah3008
