### ISSUE TITLE
Bug:  Two buttons are showing page not found

### ISSUE THREAD

**Issue by sketchomania** [moja-global/community-website#374]
### Describe the bug.

In **Know the Community** section under **Miscellaneous**, `Frequently Asked Questions`  and `Join moja global` buttons are showing `Page not found` when clicked.

![issue-6](https://user-images.githubusercontent.com/77732479/202348067-218deb54-2850-4c29-acd5-42bd48b10d12.png)
![issue-1](https://user-images.githubusercontent.com/77732479/202348087-6ea91b32-e129-4c13-8f05-2ad0f471a2b2.png)

## Both buttons should navigate to their named section
- First I will check If the url of the both the pages are chnaged
- Or if pages are not present then I will create, according to guide if available.

## Both button should navigate to their corresponding sections:
- `Frequently Asked Questions` button should navigate to **Frequently Asked Questions** Page.
- `Join moja global` button should navigate to **Join moja global (slack)** Page.

### Screenshots.

These two buttons: 
![issue-4](https://user-images.githubusercontent.com/77732479/202347263-5c95a920-2db6-4692-8f06-516168f08811.png)
![issue-5](https://user-images.githubusercontent.com/77732479/202347271-685e47a9-878f-4975-b272-d8c9c0afb854.png)

### Operating Environment

Google Chrome Version: 107.0.5304.107 , Windows 11, Version: 22H2, OS build: 22621.819

**Comment by sketchomania** [comment]
I would like to work on this issue

**Comment by Aditya9764** [comment]
Hey Team, I would love to work on this feature. Tech stack seems right fit for me.
Can you please assign me this issue?
I will try to add correct url of page

**Comment by meenaljain0303** [comment]
I can help with the issue

**Comment by ksba2004** [comment]
I would like to work on this issue. Can I please be assigned?
