### ISSUE TITLE
Bug: The GCBM link is not working and not showing up as we click on the GCBM on the Projects section of "Know the community"

### ISSUE THREAD

**Issue by ItsRoy69** [moja-global/community-website#375]
### Describe the bug.

The GCBM link is not working and not showing up as we click on the GCBM on the Projects section of footer . The link is broken,  I can work on the issue and fix it.

### Describe the steps to reproduce the behavior.

Proper link i.e "https://community.moja.global/docs/GCBM/GCBM" should be given instead of "https://community.moja.global/docs/GCBM/About"

### Expected behavior.

![image](https://user-images.githubusercontent.com/78967360/204133932-978f2bec-d394-4103-87c0-b6cb4b010a93.png)

This should show up instead of 

![image](https://user-images.githubusercontent.com/78967360/204133948-468f8a63-db63-4f74-b27d-dbd7f5535fd2.png)

### Operating Environment

Windows 10

**Comment by ItsRoy69** [comment]
I can fix this up

**Comment by ARYA-RAY** [comment]
can someone assign me this issue?

**Comment by ItsRoy69** [comment]
@HarshCasper or any other mentors kindly look into this issue and it will bd great if you assign me
