### ISSUE TITLE
Bug: Broken links on the community website

### ISSUE THREAD

**Issue by ansharora28** [moja-global/community-website#384]
### Describe the bug.

The FAQs button is broken.

### Describe the steps to reproduce the behavior.

Scroll down to the footer and click on the FAQs button.

### Expected behavior.

The button should lead to the[ FAQs page](https://docs.moja.global/en/add_instructions_gdal/faq.html) of moja global.
Please let me know if this is the correct URL or if I'm wrong.

![image](https://user-images.githubusercontent.com/89684245/212529360-97d55817-5cbc-4cb7-af55-c27ec24bb331.png)

### Screenshots.

Current behavior- 
![image](https://user-images.githubusercontent.com/89684245/212529372-322403a8-3adf-4486-9849-9621dc94f374.png)

### Operating Environment

Windows 11. I tried reproducing the bug on chrome and brave browser.

**Comment by ansharora28** [comment]
I would like to work on this issue

**Comment by ansharora28** [comment]
Sure, here it is 
![image](https://user-images.githubusercontent.com/89684245/212609996-4d5d7f84-34b9-4926-a622-56d08f3594f9.png)

**Comment by Arya-Gupta** [comment]
I am interested in working on this issue. Can I please be assigned? @HarshCasper

**Comment by HarshCasper** [comment]
@ansharora28 I have assigned the issue to @Arya-Gupta. Can you please find something else to work on, or please DM me on Slack to discuss about what you can work upon 😄 (there are a lot of things to fix!)
