### ISSUE TITLE
Bug: Text breaks for certain devices

### ISSUE THREAD

**Issue by developer-diganta** [moja-global/community-website#386]
### Describe the bug.

For certain device widths, the word 'contributors' breaks with s coming in next line.

### Describe the steps to reproduce the behavior.

Using inspect tools, check the webpage for Samsung Galaxy S8+.

### Expected behavior.

The word contributors should stay as one.

### Screenshots.

![image](https://user-images.githubusercontent.com/65999534/212739238-b20c7119-cc29-4298-9318-86b250e09b0e.png)

### Operating Environment

Windows 11. I tried reproducing the bug on Chrome.

### Additional Information

I would love to work on this issue if it is valid.

**Comment by ksba2004** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by arjun26122002** [comment]
Hi sir,
I want to work on this issue, can you please assign me?
