### ISSUE TITLE
Feature Request: Proper Alignment of the text and Navbar fix

### ISSUE THREAD

**Issue by ksba2004** [moja-global/community-website#387]
### Is your feature request related to a problem? Please describe.

It looks that the nav bar is not fixed at the top, whenever a user scrolls down the page, the nav bar gets removed from top and whenever we scroll down, it again reappears.
I also tried to make the text alignment in "HomePageFeatures" section of the code.
Apart from this, the boxes of "Know Our Projects", "Watch the tutorials" and "Demo Days" do not have the same length, it would much prettier if all the boxes have same length.

### Describe the solution you'd like.

The Nav Bar could be fixed using CSS.
Text alignment could be done which would make the website look much prettier.
![Screenshot (13)](https://user-images.githubusercontent.com/99543379/212808779-23e3a44d-108c-4586-bea0-1383c9218726.png)
![Screenshot (12)](https://user-images.githubusercontent.com/99543379/212808802-760ca7dc-8d84-4af2-aac7-879093345d31.png)

### Describe alternatives you've considered

I considered making text alignment to left.

**Comment by ksba2004** [comment]
I would like to work on this if it is a relevant enhancement, along with with it, I would work on nav bar as well. 
Please assign this to me if this enhancement work for the community.

**Comment by arjun26122002** [comment]
Hi sir,
I want to work on this issue, can you please assign me?
