### ISSUE TITLE
Bug: "Working Groups" spelling mistake on footer 

### ISSUE THREAD

**Issue by ksba2004** [moja-global/community-website#389]
### Describe the bug.

While scrolling down the page of our community website, I saw some error in spelling of "Working Groups" as "Workiing Groups" of footer, and capitalization error in "Governance Model" as "Governance model" and "Contributing Guidelines" as "Contributing guidelines" in footer.

### Describe the steps to reproduce the behavior.

I tried to correct the spelling in the code base of moja global community website.

### Expected behavior.

As I mentioned in enhancement of #387, I tried to fix the Navbar as well. I also have corrected the specking errors too present in the footer.

### Screenshots.

Here is the recording of the errored website:

https://user-images.githubusercontent.com/99543379/212988703-d09f0d6c-b5e7-4652-8842-a59c11fd1b68.mp4

Here is the recording of error free:

https://user-images.githubusercontent.com/99543379/212989290-999a9eca-ec10-4066-84cd-f4794b35526d.mp4

### Operating Environment

Windows 11

### Additional Information

If it is a useful bug for the community and the video shown above works well for the community, then please assign me this issue.

**Comment by ksba2004** [comment]
I would like to work on this issue, please assign this to me.

**Comment by padmajabhol** [comment]
Please correct the spelling error, I don't think we need to change anything with the capitalization.

**Comment by sambhavgupta0705** [comment]
@ksba2004 are you still working on this issue?

**Comment by ksba2004** [comment]
@sambhavgupta0705 this issue has already been worked upon, please find any other issue on which you can work.
