### ISSUE TITLE
feat: Add twitter card and moja global logo to the Open Graph Image metadata

### ISSUE THREAD

**Issue by iamrajiv** [moja-global/community-website#39]
## Description

When we share [https://moja-global.vercel.app/](https://moja-global.vercel.app/) over social media like Twitter, it is good that the card they generate for the link has useful information.

![Screenshot 2021-08-02 at 2 57 53 PM](https://user-images.githubusercontent.com/42106787/127838522-5d07c2a7-4ad7-4587-853f-6cc4da9066aa.jpg)

Currently, Twitter does not render and get any image to use for [https://moja-global.vercel.app/](https://moja-global.vercel.app/).

## Possible Implementation:

Add an [og:image](https://ogp.me) metadata to the website and use the moja global logo. Use png instead of SVG here.

## Context:

Use https://cards-dev.twitter.com/validator to validate results.

**Comment by Siddhant-K-code** [comment]
Apart from the **moja-global** image, what other details/text should be there?

also, https://contributor-website-v2.vercel.app/ is giving `Error 404` as of now

**Comment by iamrajiv** [comment]
@Siddhant-K-code I have updated the links. You just have to add `metadatas` in `docusaurus.config.js`. Also, you can use this image [https://github.com/moja-global/community-website/blob/main/website/static/img/logo.png](https://github.com/moja-global/community-website/blob/main/website/static/img/logo.png).

**Comment by sarthakkundra** [comment]
Let's worry about it once we officially host the website.
