### ISSUE TITLE
Bug: The link are not working and not showing up as we click on the the links under the How To Guides of "Know the community"

### ISSUE THREAD

**Issue by ItsRoy69** [moja-global/community-website#390]
### Describe the bug.

The "Writing documentation", "FLINT Prerequisite", "FLINT Development Setup", "GCBM Development Setup", "GitHub Workflow" links are not working and not showing up as we click on them on the How To Guides section . The links are broken, I can work on the issue and fix it.

### Describe the steps to reproduce the behavior.

Proper link i.e "https://docs.moja.global/en/master/FLINT/FLINTPrerequisites/index.html" should be given instead of "https://docs.moja.global/en/latest/prerequisites/index.html"

Proper link i.e "https://docs.moja.global/en/master/FLINT/FLINTDevelopmentSetup/index.html" should be given instead of "https://docs.moja.global/en/latest/DevelopmentSetup/index.html"

Proper link i.e "https://docs.moja.global/en/master/GCBM/GCBMDevelopmentSetup/index.html" should be given instead of "https://docs.moja.global/en/latest/GCBMDevelopmentSetup/index.html"

Proper link i.e "https://docs.moja.global/en/master/Guidelines/DeveloperWorkflow/index.html" should be given instead of "https://docs.moja.global/en/latest/DeveloperWorkflow/index.html"

Proper link i.e "https://docs.moja.global/en/master/Guidelines/DocumentationStyleGuide/index.html" should be given instead of "https://docs.moja.global/en/latest/DocumentationStyleGuide/index.html"

### Expected behavior.

![image](https://user-images.githubusercontent.com/78967360/213194373-eddac4c5-f22f-49b4-b967-a9d4369a7aab.png)
This should show up instead of
![image](https://user-images.githubusercontent.com/78967360/213194460-94f20dc4-011e-42b4-8c69-8895e1f23d8c.png)

### Operating Environment

Windows 10

### Additional Information

I can fix this up if any maintainers can assign me

**Comment by ItsRoy69** [comment]
I would like to work on this, if you think the feature is of relevance and would be a good addition to the website.

**Comment by Palaksharma23** [comment]
Yes @ItsRoy69, you can start working on this.
