### ISSUE TITLE
Feature Request: Make the Moja Global Logo more visible in the top menu bar

### ISSUE THREAD

**Issue by Aarthy153** [moja-global/community-website#393]
### Is your feature request related to a problem? Please describe.

The idea is to make the Moja Global logo more visible. Currently, the logo is placed somewhat small and the Community Button seems to be more highlighted. 

### Describe the solution you'd like.

The approach is to adjust the size of the logo image

### Additional context.

I am Working on this currently and will soon give a PR.

**Comment by Nitishupkr** [comment]
can u assign me this issue

**Comment by Aarthy153** [comment]
Hi, I am working on this for WOC.
