### ISSUE TITLE
Feature Request: Creating Card views and enhancing the content structure

### ISSUE THREAD

**Issue by Aarthy153** [moja-global/community-website#394]
### Is your feature request related to a problem? Please describe.

Creating Card views to place these plain structured data with a trendy look.

![image](https://user-images.githubusercontent.com/69035013/213216053-2476ae78-bcb3-4510-808b-8bccbfe700a5.png)

The idea is to create card views in order to make these plain structured texts more attractive. The existing system has a very simple UI format. 

### Describe the solution you'd like.

The proposed system will contain a more trendy UI with the content placed inside card views.

### Additional context.

I am currently working on this feature and will give a PR soon.

**Comment by Aadijindal07** [comment]
If it is not solved i would love to work on it kindly assign

what i will do ?
-> this is a basic layout which i will follow dont worry about styling this is a example i am pretty sure yu gonna love it

//
<div class="card">
  <img src="image.jpg" alt="Image">
  <div class="card-body">
    <h4 class="card-title">Card Title</h4>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  overflow: hidden;
}

.card img {
  height: 200px;
  width: 100%;
  object-fit: cover;
}

.card-body {
  padding: 2px 16px;
}

@media (max-width: 576px) {
  .card {
    max-width: 100%;
  }
}

**Comment by Aadijindal07** [comment]
If it is not solved i would love to work on it kindly assign 
This will make the information displayed more attractive and visually appealing. The cards will contain the required information in an organized manner, making it easier to read. Additionally, the card view will also contain a "read more" button, which will allow the user to read more about the topic. The card view will also contain an image related to the topic, which will make it more visually appealing. Lastly, the card view will also contain a link to the related page, which will make it easier for the user to navigate to the page they are interested in. So am very interested so kindly assign

**Comment by ConnectBhawna** [comment]
@Aarthy153 Can you please assign me this issue?
I would like to work on this issue :)

**Comment by Aarthy153** [comment]
Hi @ConnectBhawna , I am working on this for WOC.
