### ISSUE TITLE
Feature Request:  Correct the size of the Moja Global brand image in the index page

### ISSUE THREAD

**Issue by Aarthy153** [moja-global/community-website#395]
### Is your feature request related to a problem? Please describe.

Currently, the image is placed like this which gives a separate light square placed on the image. 

![image](https://user-images.githubusercontent.com/69035013/213217354-be481e45-06bd-4721-824b-fe74074626ae.png)

### Describe the solution you'd like.

The suggested approach is to correct the size so that the whole image will be visible, something like this!

![image](https://user-images.githubusercontent.com/69035013/213217517-6853f1db-9308-4ba6-a99c-d89108924ca9.png)

### Additional context.

I am working on this issue and will give a PR soon.

**Comment by Aadijindal07** [comment]
I would like to work on it so kindly assign me .I would be honored to work on it

**Comment by prernadabi23** [comment]
Hello @Aarthy153, I would like to work on this issue.
