### ISSUE TITLE
Feature Request: Create a vertical border in the blogs section

### ISSUE THREAD

**Issue by Aarthy153** [moja-global/community-website#396]
### Is your feature request related to a problem? Please describe.

Currently, the blog section does not contain a vertical divider between the topics and the content. 

![image](https://user-images.githubusercontent.com/69035013/213219579-55a42fa2-e46a-44f0-824c-c599fd5ebbec.png)

### Describe the solution you'd like.

The suggested approach is to code a divider in order to divide the topics and the content, something like this!

![image](https://user-images.githubusercontent.com/69035013/213219872-9fd2afd8-db6a-47ed-895b-e6311ab77c05.png)

### Additional context.

I am working on this issue and will give a PR soon.

**Comment by Aadijindal07** [comment]
hello if you are not working on it i would love to contribute so kindly assign me

**Comment by prernadabi23** [comment]
Hello, @Aarthy153 I would like to work on this issue, please assign this to me.
