### ISSUE TITLE
Feature Request: Developing a responsive feedback forum for the website

### ISSUE THREAD

**Issue by Aarthy153** [moja-global/community-website#397]
### Is your feature request related to a problem? Please describe.

The approach aims to construct a responsive feedback form on the website so that everyone who is a part of the Moja Global Community can give their valuable feedback to help grow the organization. 

![image](https://user-images.githubusercontent.com/69035013/213226568-49023d8e-a5d8-4004-ab3c-8b8b9be00ecc.png)

### Describe the solution you'd like.

This is the sample template I have created for the feedback section. This is not the exact thing that will be implemented, this will be formatted according to the color theory and the description will be changed accordingly. 

![image](https://user-images.githubusercontent.com/69035013/213226985-f04bbed4-e32d-4357-b7cc-51b487654202.png)

### Additional context.

I am working on this issue and will give a PR soon.

**Comment by Aadijindal07** [comment]
I would love to contribute so kindly assign me it would be my pleasure to work on it

**Comment by Aarthy153** [comment]
Hi, @Aadijindal07 Kindly see the issue's additional comments. I have created issues to work for WOC. My coding period will start in a day or two. Kindly take up other issues that aren't created by me! Thank you so much :)

**Comment by Aadijindal07** [comment]
hi btw can you provide me some help like I know how to solve things but am new to gsoc, contribution etc.  and main problem is no one is assigning me any issue only 1 did and he was impressed with me but its not enough for gsoc
