### ISSUE TITLE
Feature Request: Publish blogs with SEO optimisation

### ISSUE THREAD

**Issue by Aarthy153** [moja-global/community-website#398]
### Is your feature request related to a problem? Please describe.

Draft Blogs will be published with SEO optimization. The idea is to develop blogs for the Moja Global Community website and do SEO optimization in order to drive more customers/visitors. 
As far as explored, the community website needs content/blogs for the following pages : 
https://community.moja.global/tutorial/tutorial-introduction - This section only contains the title and the header. The appropriate content/media will be added as per the instructions from the community. 

https://community.moja.global/blog - This section only contains content about GSoC and does not contain common blogs about the Moja Global community. Trending blog posts related to the Moja global organization will be added. The idea is to add blogs that would be helpful for clients/contributors to know about the services of the company very well. 

https://community.moja.global/community/technical-steering-committee - This section also only contains the header. 

### Describe the solution you'd like.

Ideas for writing efficient content/blogs during the contribution phase:

- Onpage SEO
- Offpage SEO
- Local SEO
- Keyword research
- Backlinking
- Content strategy
- Conversion Rate Optimisation

### Additional context.

I am working on adding this feature/enhancement and will give a PR soon

**Comment by ksba2004** [comment]
I would like to work on this, if it has not been done till now.
Can you please assign this to me @Aarthy153 ?
