### ISSUE TITLE
Bug: Fix The alignment of social links for mobile devices

### ISSUE THREAD

**Issue by AFZL210** [moja-global/community-website#402]
### Describe the bug.

On Mobile Devices the social icons are not aligned to the left after a line break

### Describe the steps to reproduce the behavior.

write CSS media query to align the social icons for small screens

### Expected behavior.

social icons aligned left side

### Screenshots.

![](https://res.cloudinary.com/primeflix/image/upload/v1674312776/mob_fpfrjc.png)

### Operating Environment

Windows 10 Pro

**Comment by SubhamB2003** [comment]
Hey, Is this issue still open?  Can you assign the issue to me?
