### ISSUE TITLE
Feature Request: Introduction to moja global tutorials

### ISSUE THREAD

**Issue by ItsRoy69** [moja-global/community-website#409]
### Is your feature request related to a problem? Please describe.

When we visit the Introduction to moja global tutorials page i.e "https://community.moja.global/tutorial/tutorial-introduction" we get to see ![image](https://user-images.githubusercontent.com/78967360/213984228-7528f4c2-a349-42d8-b21e-100b0a72c03f.png)

This doesn't talk or shows any tutorial videos that will be helpful

### Describe the solution you'd like.

 Thus it would've been great if any tutorial videos were attached firectly from youtube and presented directly to the site

### Additional context.

I can work on this issue and provide some designs that can be made as well as code.

**Comment by MonalikaPatnaik** [comment]
Heyy!!
I would like to work on this issue! Kindly assign me!
Thanks!

**Comment by prernadabi23** [comment]
Hello, @ItsRoy69 I would like to work on this issue.
