### ISSUE TITLE
Documentation: moja-global charter link is not working

### ISSUE THREAD

**Issue by ItsRoy69** [moja-global/community-website#410]
### What is the current documentation state?

In the website, when I click on "moja global charter" inside "https://community.moja.global/docs/about-moja-global" page, I observed that read the moja-global charter link when clicked is not working and gives a page not found an error

![image](https://user-images.githubusercontent.com/78967360/213985193-68715d25-5ff1-4a3c-ae1e-7c5612ff32bb.png)

### Where is this stated?

![image](https://user-images.githubusercontent.com/78967360/213985561-e9ffdb0e-6e83-459f-935e-a66abcc3de29.png)

### Why do you want to improve the statement?

Attach the "https://github.com/moja-global/About_moja_global/blob/master/Governance/moja-global-charter.pdf" link instead of https://community.moja.global/static/moja-global-charter.pdf

### Proposed Statement
I can work on this issue
_No response_

### Additional context.
I can work on this issue

**Comment by Arya-Gupta** [comment]
Hey, I am interested in working on this issue. Can I be assigned?

**Comment by ksba2004** [comment]
I would like to work on this issue. Can you assign this to me @ItsRoy69 ?

**Comment by AFZL210** [comment]
this can be easily fixed, i would love to work on this

**Comment by AFZL210** [comment]
i tried to change the path of pdf file and added type attribute also but when I tested it on GitPod its working fine but its not working after deploying it on vercel

**Comment by HarshCasper** [comment]
Hi @AFZL210 — Please avoid working on issues that have not yet been assigned to anyone else. In this case, @ItsRoy69 already requested for assignment, and I complied with that!

**Comment by AFZL210** [comment]
i apologize @HarshCasper
