### ISSUE TITLE
Adding a blog about Moja Global's involvement in Open Source Day 2022

### ISSUE THREAD

**Issue by abhilipsasahoo03** [moja-global/community-website#415]
### What is the current documentation state?

# Description

As discussed earlier, I would like to add an 'OSD 2022 Recap' blog regarding Moja Global's involvement in Open Source Day 2022.

### Additional context.

@HarshCasper I know this task has been pending since a long time, so I'd like to work on this!

**Comment by Nitishupkr** [comment]
can u assign me this issue ?

**Comment by abhilipsasahoo03** [comment]
> can u assign me this issue ?
> 

Hi the PR for this issue has already been created and approved. Feel free to take up any other issue. :)
