### ISSUE TITLE
Bug: Link is not Working in page exchange 

### ISSUE THREAD

**Issue by jigarvyasidea** [moja-global/community-website#420]
### Describe the bug.

When clicking on the FAQ page, the page does not open properly.
![Web capture_26-1-2023_11324_docs moja global](https://user-images.githubusercontent.com/80967728/214767348-739b1de9-6c77-4c48-9796-f8cd0f1ecb23.jpeg)

### Operating Environment

cloud

**Comment by MonalikaPatnaik** [comment]
Heyy!!
I think you are talking about the link in footer..It works for me!
Let me know if you are referencing any other faq link in website! I would love to work on this issue..

![image](https://user-images.githubusercontent.com/99353300/217298174-3630cd5d-c906-4f36-a391-ab8e2b65b829.png)
