### ISSUE TITLE
Bug: Bug to background color footer content in not visible 

### ISSUE THREAD

**Issue by jigarvyasidea** [moja-global/community-website#421]
### Describe the bug. :- footer section content not visible 

![Web capture_26-1-2023_12045_moja global](https://user-images.githubusercontent.com/80967728/214772430-589f7b03-8036-4343-aef2-2b699ef4d114.jpeg)

### Do changes 

change the background. color  

###Note 
make sure bg color is black.

**Comment by azr-arch** [comment]
color of "copyright" part or color of whole background ?

**Comment by azr-arch** [comment]
in developer tools  class name of footer container is element-overlay 
but i am unable to find same class in source code css files 

i am a beginner help me !

**Comment by DevKartikBhardwaj** [comment]
i want to contribute please assign this task to me

**Comment by SandhyaR1007** [comment]
Hi, I want to contribute to this, Please assign this task.

**Comment by thisiskaransgit** [comment]
Hey @jigarvyasidea, the issue you're referring to is not related to  the [community-website](https://community.moja.global/), it's regarding the official [moja global](https://moja.global/) website, which is **not** open-sourced, so close this issue and it would be great if you share about this in the slack
