### ISSUE TITLE
Bug: On hovering the content inside button is not visible

### ISSUE THREAD

**Issue by DevKartikBhardwaj** [moja-global/community-website#422]
On hovering the content inside button is not visible in communtity website home page!!

### Expected behavior.

I expected that on hovering the text inside this button becomes white or any color that's clearly visible!

### Screenshots.

![button_bug](https://user-images.githubusercontent.com/102840713/214846086-aa2b016f-b951-4ae5-b643-b76d5e52c4ab.jpg)

**Comment by DevKartikBhardwaj** [comment]
yes i want to claim this

**Comment by jigarvyasidea** [comment]
Assign me i want to work on this issue @Namyalg  @DevKartikBhardwaj

**Comment by Aadijindal07** [comment]
See this issue have many solution one possible could be 
button:hover {
  color: white; /* Change to any color of your choice */
}
but to know more properly please assign me i would love to work on it moreover am short on contribution so kindly assign me

**Comment by MonalikaPatnaik** [comment]
Hey!! I would like to work on this issue!
Thanks!
