### ISSUE TITLE
Documentation: Grammatical errors in code of conduct

### ISSUE THREAD

**Issue by Arya-Gupta** [moja-global/community-website#423]
### What is the current documentation state?

Our Pledge[​](https://community.moja.global/community/code-of-conduct#our-pledge)
In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

Our Responsibilities[​](https://community.moja.global/community/code-of-conduct#our-responsibilities)
Project maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior.
Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.

Enforcement[​](https://community.moja.global/community/code-of-conduct#enforcement)
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [guy@moja.global.](mailto:guy@moja.global.) All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.
Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project's leadership.

### Where is this stated?

https://community.moja.global/community/code-of-conduct

### Why do you want to improve the statement?

The statement contains grammatical errors.

### Proposed Statement

Our Pledge[​](https://community.moja.global/community/code-of-conduct#our-pledge)
In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to make participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

Our Responsibilities[​](https://community.moja.global/community/code-of-conduct#our-responsibilities)
Project maintainers are responsible for clarifying the standards of acceptable behavior and are expected to take appropriate and fair corrective action in response to any instances of unacceptable behavior.
Project maintainers have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned with this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviors that they deem inappropriate, threatening, offensive, or harmful.

Enforcement[​](https://community.moja.global/community/code-of-conduct#enforcement)
Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [guy@moja.global.](mailto:guy@moja.global.) All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality concerning the reporter of an incident. Further details of specific enforcement policies may be posted separately.
Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project's leadership.

### Additional context.

I would like to work on this issue. Can I be assigned?

**Comment by vedant-z** [comment]
@Arya-Gupta Please assign me this issue.

**Comment by prernadabi23** [comment]
@Arya-Gupta Please assign this issue to me.
