### ISSUE TITLE
Bug: Link to the FLINT Example setup guide at moja global docs not working

### ISSUE THREAD

**Issue by jigarvyasidea** [moja-global/community-website#424]
### Describe the bug.

Link to the FLINT Example setup guide at moja global docs not working 

### Screenshots.

https://docs.moja.global/en/latest/DevelopmentSetup/FLINT.example_installation.html
![Web capture_30-1-2023_115355_docs moja global](https://user-images.githubusercontent.com/80967728/215403349-6c7dba31-bdbf-4b67-bec6-3bfd781492e8.jpeg)

**Comment by vedant-z** [comment]
@jigarvyasidea I am willing to work on this.

**Comment by thisiskaransgit** [comment]
Hey @jigarvyasidea, is this issue related to [community-website](https://community.moja.global/) or not, if yes, could you please update the issue with *steps to reproduce bug* as I wasn't able to reproduce it.
