### ISSUE TITLE
Bug: On hovering the third button, text is not seen

### ISSUE THREAD

**Issue by psankhe28** [moja-global/community-website#431]
### Describe the bug.

 On hovering the third button i.e Demo Days button, text is not seen. This is because of the hover effect.

### Describe the steps to reproduce the behavior.

Change the css

### Expected behavior.

It should be similar to the other 2 buttons

### Screenshots.

![image](https://user-images.githubusercontent.com/84843461/218440856-eeb44d12-4592-4919-a513-485835f50e51.png)

### Operating Environment

Windows

### Additional Information

I would like to work on this issue

**Comment by sambhavgupta0705** [comment]
This issue has been already raised via [#422 ](https://github.com/moja-global/community-website/issues/422)

**Comment by niranjan-kurhade** [comment]
Hey can I work on issue? If yes Please assign it to me.

**Comment by samyakshah3008** [comment]
Can I work on this issue? Please assign to me.

**Comment by sambhavgupta0705** [comment]
still relevant
