### ISSUE TITLE
Feature Request: The mentoship page can be updated with new data

### ISSUE THREAD

**Issue by sambhavgupta0705** [moja-global/community-website#432]
### Is your feature request related to a problem? Please describe.

The GSOD and GSOC section are still having 2021 stats. 

### Describe the solution you'd like.

We can update it with new stats of 2022.

### Additional context.

![image](https://user-images.githubusercontent.com/81870866/219833978-e1437610-046d-47bd-8658-317665dfb30e.png)

**Comment by sonai99** [comment]
Hey @sambhavgupta0705 i would like to work on this, how can i get started?

**Comment by sambhavgupta0705** [comment]
Hey @sonai99 ,one of maintainer has to apporve this issue first 
cc: @HarshCasper

**Comment by sonai99** [comment]
Hey @sambhavgupta0705 can you please tell me how can i join this community, i want to contribute.
The slack link seems not to be working for me.
