### ISSUE TITLE
The Community Website link have Error

### ISSUE THREAD

**Issue by Subhradeep10** [moja-global/community-website#56]
It's Showing Error 404 not found!

![Screenshot from 2021-08-12 12-58-31](https://user-images.githubusercontent.com/70656957/129155879-4c89be2d-c63d-4050-b318-5dfc6d24334e.png)

**Comment by HarshCasper** [comment]
Hi @Subhradeep10 

This is the correct link: https://contributor-website-v2-6iaupqwgk-moja-global.vercel.app/ 

We will update the link once the website is ready for release :)
