### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by ErrolFernandes** [moja-global/community-website#62]
The links in moja.global website of cookies and privacy policy are not working.

P.s.:I'm not sure if this is a right repository for this issue.

**Comment by alokprinc** [comment]
i would like to work.
can you show me ropes for this issue

**Comment by AmanPathak-dev** [comment]
assign me 
i will fix it 
if you assign me the role to fix it

**Comment by HarshCasper** [comment]
Hi all,

This repository doesn't concern the actual moja global website. If you happen to find any bugs or issues on the community website (community.moja.global), please feel free to create an issue.
