### ISSUE TITLE
Adding Open Graph image metadata in the docusaurus site of community website

### ISSUE THREAD

**Issue by iamrajiv** [moja-global/community-website#63]
## Description

When we share https://community.moja.global/ over social media, it is good that the card they generate for the link has useful information.

## References

- Use https://developers.facebook.com/tools/debug/ to validate results for Facebook.
- Use https://www.linkedin.com/post-inspector/ to validate results for LinkedIn.
- Use https://cards-dev.twitter.com/validator to validate results for Twitter.

**Comment by iamrajiv** [comment]
@HarshCasper I want to work on this

**Comment by sarthakkundra** [comment]
Go ahead @iamrajiv! :)
