### ISSUE TITLE
Add SEO tags to the community website

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#65]
## Description

Add SEO tags to the community website. Docusaurus takes care of both site level SEO and page specific SEO. We would ideally like to have site level SEO to help users reach our site and page specific SEO to help them find relevant information.

Site level SEO can be implemented by adding `docusaurus.config.js` while page specific SEO can be implemented by adding fields in your doc's front matter:

```mdx
---
keywords:
  - docs
  - docusaurus
description: How do I find you when I cannot solve this problem
image: https://i.imgur.com/mErPwqL.png
---
```

We would also like to have customized SEO by adding the Head component from `@docusaurus/Head`.

```jsx
import Head from '@docusaurus/Head';

const MySEO = () => (
  <>
    <Head>
      <meta property="og:description" content={'My custom description'} />
    </Head>
  </>
);
```

**Comment by faisaljamil25** [comment]
@HarshCasper can you assign this to me?

**Comment by faisaljamil25** [comment]
>https://github.com/moja-global/community-website/blob/cc48054ce038256eff85eaa90573a87bf05fc0b4/website/src/pages/index.js#L100

@HarshCasper I'm a bit confused how can I add customized SEO in the description prop as it's take string input?

**Comment by HarshCasper** [comment]
> > https://github.com/moja-global/community-website/blob/cc48054ce038256eff85eaa90573a87bf05fc0b4/website/src/pages/index.js#L100
> 
> @HarshCasper I'm a bit confused how can I add customized SEO in the description prop as it's take string input?

Please look at my issue description.
