### ISSUE TITLE
Refactor Issue templates to use GitHub Forms

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#66]
## Description

Markdown templates often made it difficult to capture the whole context, by expecting the contributors to read the markup, uncomment lines and delete relevant context. 

Issue forms beta was released for public repositories last month, as mentioned by GitHub on this [blog](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/). We would like to migrate the issue templates to YAML-based forms which are easy to fill up and maintain, helping us capture relevant context.

Check out how these are implemented on other moja global projects: 

- https://github.com/moja-global/FLINT-UI/tree/master/.github/ISSUE_TEMPLATE
- https://github.com/moja-global/FLINT.JSON_Interface/tree/master/.github/ISSUE_TEMPLATE

**Comment by Megatank58** [comment]
I would like to do this

**Comment by HarshCasper** [comment]
> I would like to do this

Please let me know if you need any help or assistance on the same. You can alternatively reach out to me on Slack for any questions.

**Comment by Megatank58** [comment]
#71 fixes this
