### ISSUE TITLE
Add LightHouse CI for the Community Website

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#68]
## Description

The LightHouse CI should ideally:

- Add `lighthousesrc.json` to identify the metrics we are looking to track.
- Use the `aaron-binary/vercel-preview-url-action@v0.0.3` action to grab the deployed preview link.
- Use the `treosh/lighthouse-ci-action` to audit the preview link through LightHouse and upload generated files as artifact.
- Use the `actions/github-script` and `marocchino/sticky-pull-request-comment` to mark the performance as a PR comment.

Some inspiration can be fetched from the following PR by @sarthakkundra on Docusaurus:

- https://github.com/facebook/docusaurus/pull/3761

Note that it is using Netlify previews, instead of standard Vercel previews and it can be tweaked further for our use-case.

**Comment by rutujaingole** [comment]
@HarshCasper  I'd like to work on this.
