### ISSUE TITLE
Improve the Community Website Footer

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#69]
## Description

The current state of the footer on the community website is:

![image](https://user-images.githubusercontent.com/47351025/135703779-15f58b29-ebb8-425c-8dba-fda0ad0f3cba.png)

We would like to add more references here for sharing better context with our community members. Ideally we would like to have the following sections:

#### Community

- [ ] Blogs: https://community.moja.global/blog
- [ ] News: https://moja.global/news/
- [ ] Programs: https://docs.moja.global/en/latest/contact.html#outreach-and-student-programs
- [ ] FAQs: https://docs.moja.global/en/latest/faq.html
- [ ] Slack: mojaglobal.slack.com

#### Projects

- [ ] FLINT
- [ ] FLINT UI
- [ ] FLINT Reporting Tool
- [ ] Taswira
- [ ] FLINT JSON Editor
- [ ] FLINT Cloud

NOTE: Link to their official docs instead of GitHub repos wherever relevant.

#### Getting started

- [ ] What is FLINT?
- [ ] About moja global (Link to official repo)
- [ ] News Letter: https://global.us13.list-manage.com/subscribe?u=d8a187fa0dfae0bafe4bc69cc&id=cbfdc2d476

#### Socials

**Comment by Ishika414** [comment]
I would like to work on this issue

**Comment by HarshCasper** [comment]
> I would like to work on this issue

Please let me know if you need any assistance or help. You can alternatively reach out to me on Slack as well.

**Comment by Ishika414** [comment]
Hi! i am not able to find the file containing the footer. Could you please help me with that.

**Comment by HarshCasper** [comment]
> Hi! i am not able to find the file containing the footer. Could you please help me with that.

Here you go: https://github.com/moja-global/community-website/blob/9683c920cfca58903f810c53135f46b994de17ca/website/docusaurus.config.js#L35
