### ISSUE TITLE
Fix `sitemap.xml` and add `robots.txt` on the community website

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#72]
## Description

Currently, our `sitemap.xml` isn't behaving as expected: https://community.moja.global/sitemap.xml

We would ideally like to fix this error. We would also like to add the `robots.txt` by referencing the agents that can crawl the website. Refer [this](https://github.com/facebook/docusaurus/discussions/4033).

**Comment by eemike07** [comment]
Hello, I would like to tackle this.  What's the expected behavior? 
Is it something like this?  https://www.rocktherankings.com/page-sitemap.xml

**Comment by HarshCasper** [comment]
> Hello, I would like to tackle this. What's the expected behavior? Is it something like this? https://www.rocktherankings.com/page-sitemap.xml

Exactly. This would be an easy fix by editing this line: https://github.com/moja-global/community-website/blob/9683c920cfca58903f810c53135f46b994de17ca/website/docusaurus.config.js#L5

**Comment by HarshCasper** [comment]
Hi @eemike07 

You can also have a look at the same: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap

**Comment by eemike07** [comment]
For the `robots.txt`, are there any bots you'd want to disallow?  Or just keep defaults for now?
```
User-agent: Googlebot
Disallow: /nogooglebot/

User-agent: *
Allow: /

Sitemap: https://community.moja.global/sitemap.xml
```
I know that the following is by default -
```
User-agent: *
Allow: /
```

**Comment by HarshCasper** [comment]
@eemike07 Keeping default would be good.

**Comment by eemike07** [comment]
Had to create another branch and re-submit pull request to perform the `--signoff`
