### ISSUE TITLE
Feature Request: Add Google Analytics Plugin

### ISSUE THREAD

**Issue by HarshCasper** [moja-global/community-website#77]
### Is your feature request related to a problem? Please describe.

Add and configure the [Docusaurus Plugin for Google Analytics](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics) for the community website.

### Describe the solution you'd like.

The G-Tag for [moja.global](https://moja.global) is `UA-195907568-1`. We can use the same and the Google Analytics can take care of tracking the viewers on the community website (ideally).

**Comment by faisaljamil25** [comment]
@HarshCasper I would like to work on this feature.

**Comment by HarshCasper** [comment]
> @HarshCasper I would like to work on this feature.

Thanks for taking it up! Please let me know if you need any help or assistance with the same.
